// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConnectPeerRequestV1 struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectPeerRequestV1) Reset()         { *m = ConnectPeerRequestV1{} }
func (m *ConnectPeerRequestV1) String() string { return proto.CompactTextString(m) }
func (*ConnectPeerRequestV1) ProtoMessage()    {}
func (*ConnectPeerRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *ConnectPeerRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectPeerRequestV1.Unmarshal(m, b)
}
func (m *ConnectPeerRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectPeerRequestV1.Marshal(b, m, deterministic)
}
func (m *ConnectPeerRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectPeerRequestV1.Merge(m, src)
}
func (m *ConnectPeerRequestV1) XXX_Size() int {
	return xxx_messageInfo_ConnectPeerRequestV1.Size(m)
}
func (m *ConnectPeerRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectPeerRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectPeerRequestV1 proto.InternalMessageInfo

func (m *ConnectPeerRequestV1) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type ConnectPeerResponseV1 struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectPeerResponseV1) Reset()         { *m = ConnectPeerResponseV1{} }
func (m *ConnectPeerResponseV1) String() string { return proto.CompactTextString(m) }
func (*ConnectPeerResponseV1) ProtoMessage()    {}
func (*ConnectPeerResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

func (m *ConnectPeerResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectPeerResponseV1.Unmarshal(m, b)
}
func (m *ConnectPeerResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectPeerResponseV1.Marshal(b, m, deterministic)
}
func (m *ConnectPeerResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectPeerResponseV1.Merge(m, src)
}
func (m *ConnectPeerResponseV1) XXX_Size() int {
	return xxx_messageInfo_ConnectPeerResponseV1.Size(m)
}
func (m *ConnectPeerResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectPeerResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectPeerResponseV1 proto.InternalMessageInfo

func (m *ConnectPeerResponseV1) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type PostOrderRequestV1 struct {
	MakerAsset           string   `protobuf:"bytes,1,opt,name=makerAsset,proto3" json:"makerAsset,omitempty"`
	TakerAsset           string   `protobuf:"bytes,2,opt,name=takerAsset,proto3" json:"takerAsset,omitempty"`
	Quantity             float32  `protobuf:"fixed32,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	CancelAt             string   `protobuf:"bytes,5,opt,name=cancelAt,proto3" json:"cancelAt,omitempty"`
	Memo                 string   `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostOrderRequestV1) Reset()         { *m = PostOrderRequestV1{} }
func (m *PostOrderRequestV1) String() string { return proto.CompactTextString(m) }
func (*PostOrderRequestV1) ProtoMessage()    {}
func (*PostOrderRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{2}
}

func (m *PostOrderRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOrderRequestV1.Unmarshal(m, b)
}
func (m *PostOrderRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOrderRequestV1.Marshal(b, m, deterministic)
}
func (m *PostOrderRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOrderRequestV1.Merge(m, src)
}
func (m *PostOrderRequestV1) XXX_Size() int {
	return xxx_messageInfo_PostOrderRequestV1.Size(m)
}
func (m *PostOrderRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOrderRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_PostOrderRequestV1 proto.InternalMessageInfo

func (m *PostOrderRequestV1) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *PostOrderRequestV1) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

func (m *PostOrderRequestV1) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *PostOrderRequestV1) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PostOrderRequestV1) GetCancelAt() string {
	if m != nil {
		return m.CancelAt
	}
	return ""
}

func (m *PostOrderRequestV1) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type PostOrderResponseV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserPubkey           string   `protobuf:"bytes,2,opt,name=userPubkey,proto3" json:"userPubkey,omitempty"`
	MakerAsset           string   `protobuf:"bytes,3,opt,name=makerAsset,proto3" json:"makerAsset,omitempty"`
	TakerAsset           string   `protobuf:"bytes,4,opt,name=takerAsset,proto3" json:"takerAsset,omitempty"`
	Quantity             float32  `protobuf:"fixed32,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	CancelAt             string   `protobuf:"bytes,7,opt,name=cancelAt,proto3" json:"cancelAt,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Memo                 string   `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
	Signature            []byte   `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostOrderResponseV1) Reset()         { *m = PostOrderResponseV1{} }
func (m *PostOrderResponseV1) String() string { return proto.CompactTextString(m) }
func (*PostOrderResponseV1) ProtoMessage()    {}
func (*PostOrderResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{3}
}

func (m *PostOrderResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOrderResponseV1.Unmarshal(m, b)
}
func (m *PostOrderResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOrderResponseV1.Marshal(b, m, deterministic)
}
func (m *PostOrderResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOrderResponseV1.Merge(m, src)
}
func (m *PostOrderResponseV1) XXX_Size() int {
	return xxx_messageInfo_PostOrderResponseV1.Size(m)
}
func (m *PostOrderResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOrderResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_PostOrderResponseV1 proto.InternalMessageInfo

func (m *PostOrderResponseV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PostOrderResponseV1) GetUserPubkey() string {
	if m != nil {
		return m.UserPubkey
	}
	return ""
}

func (m *PostOrderResponseV1) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *PostOrderResponseV1) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

func (m *PostOrderResponseV1) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *PostOrderResponseV1) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PostOrderResponseV1) GetCancelAt() string {
	if m != nil {
		return m.CancelAt
	}
	return ""
}

func (m *PostOrderResponseV1) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *PostOrderResponseV1) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *PostOrderResponseV1) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetOrderRequestV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserPubkey           string   `protobuf:"bytes,2,opt,name=userPubkey,proto3" json:"userPubkey,omitempty"`
	MakerAsset           string   `protobuf:"bytes,3,opt,name=makerAsset,proto3" json:"makerAsset,omitempty"`
	TakerAsset           string   `protobuf:"bytes,4,opt,name=takerAsset,proto3" json:"takerAsset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequestV1) Reset()         { *m = GetOrderRequestV1{} }
func (m *GetOrderRequestV1) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequestV1) ProtoMessage()    {}
func (*GetOrderRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{4}
}

func (m *GetOrderRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequestV1.Unmarshal(m, b)
}
func (m *GetOrderRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequestV1.Marshal(b, m, deterministic)
}
func (m *GetOrderRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequestV1.Merge(m, src)
}
func (m *GetOrderRequestV1) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequestV1.Size(m)
}
func (m *GetOrderRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequestV1 proto.InternalMessageInfo

func (m *GetOrderRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *GetOrderRequestV1) GetUserPubkey() string {
	if m != nil {
		return m.UserPubkey
	}
	return ""
}

func (m *GetOrderRequestV1) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *GetOrderRequestV1) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

type GetOrderResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserPubKey           string   `protobuf:"bytes,2,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	MakerAsset           string   `protobuf:"bytes,3,opt,name=makerAsset,proto3" json:"makerAsset,omitempty"`
	TakerAsset           string   `protobuf:"bytes,4,opt,name=takerAsset,proto3" json:"takerAsset,omitempty"`
	Quantity             float32  `protobuf:"fixed32,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	CancelAt             string   `protobuf:"bytes,7,opt,name=cancelAt,proto3" json:"cancelAt,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Memo                 string   `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
	Signature            []byte   `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	Status               string   `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{5}
}

func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(m, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *GetOrderResponse) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *GetOrderResponse) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *GetOrderResponse) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

func (m *GetOrderResponse) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *GetOrderResponse) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetOrderResponse) GetCancelAt() string {
	if m != nil {
		return m.CancelAt
	}
	return ""
}

func (m *GetOrderResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetOrderResponse) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *GetOrderResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *GetOrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetOrderResponseV1 struct {
	Responses            []*GetOrderResponse `protobuf:"bytes,1,rep,name=Responses,proto3" json:"Responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetOrderResponseV1) Reset()         { *m = GetOrderResponseV1{} }
func (m *GetOrderResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponseV1) ProtoMessage()    {}
func (*GetOrderResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{6}
}

func (m *GetOrderResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponseV1.Unmarshal(m, b)
}
func (m *GetOrderResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponseV1.Marshal(b, m, deterministic)
}
func (m *GetOrderResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponseV1.Merge(m, src)
}
func (m *GetOrderResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponseV1.Size(m)
}
func (m *GetOrderResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponseV1 proto.InternalMessageInfo

func (m *GetOrderResponseV1) GetResponses() []*GetOrderResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type FillIntentRequestV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Quantity             float32  `protobuf:"fixed32,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CancelAt             string   `protobuf:"bytes,3,opt,name=cancelAt,proto3" json:"cancelAt,omitempty"`
	Memo                 string   `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FillIntentRequestV1) Reset()         { *m = FillIntentRequestV1{} }
func (m *FillIntentRequestV1) String() string { return proto.CompactTextString(m) }
func (*FillIntentRequestV1) ProtoMessage()    {}
func (*FillIntentRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{7}
}

func (m *FillIntentRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FillIntentRequestV1.Unmarshal(m, b)
}
func (m *FillIntentRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FillIntentRequestV1.Marshal(b, m, deterministic)
}
func (m *FillIntentRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FillIntentRequestV1.Merge(m, src)
}
func (m *FillIntentRequestV1) XXX_Size() int {
	return xxx_messageInfo_FillIntentRequestV1.Size(m)
}
func (m *FillIntentRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_FillIntentRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_FillIntentRequestV1 proto.InternalMessageInfo

func (m *FillIntentRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *FillIntentRequestV1) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *FillIntentRequestV1) GetCancelAt() string {
	if m != nil {
		return m.CancelAt
	}
	return ""
}

func (m *FillIntentRequestV1) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type FillIntentResponseV1 struct {
	IntentId             string   `protobuf:"bytes,1,opt,name=intentId,proto3" json:"intentId,omitempty"`
	UserPubKey           string   `protobuf:"bytes,2,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	CpPubKey             string   `protobuf:"bytes,3,opt,name=cpPubKey,proto3" json:"cpPubKey,omitempty"`
	OrderId              string   `protobuf:"bytes,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Quantity             float32  `protobuf:"fixed32,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	MakerAsset           string   `protobuf:"bytes,7,opt,name=makerAsset,proto3" json:"makerAsset,omitempty"`
	TakerAsset           string   `protobuf:"bytes,8,opt,name=takerAsset,proto3" json:"takerAsset,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	CancelAt             string   `protobuf:"bytes,10,opt,name=cancelAt,proto3" json:"cancelAt,omitempty"`
	Memo                 string   `protobuf:"bytes,11,opt,name=memo,proto3" json:"memo,omitempty"`
	Signature            []byte   `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	Status               string   `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FillIntentResponseV1) Reset()         { *m = FillIntentResponseV1{} }
func (m *FillIntentResponseV1) String() string { return proto.CompactTextString(m) }
func (*FillIntentResponseV1) ProtoMessage()    {}
func (*FillIntentResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{8}
}

func (m *FillIntentResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FillIntentResponseV1.Unmarshal(m, b)
}
func (m *FillIntentResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FillIntentResponseV1.Marshal(b, m, deterministic)
}
func (m *FillIntentResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FillIntentResponseV1.Merge(m, src)
}
func (m *FillIntentResponseV1) XXX_Size() int {
	return xxx_messageInfo_FillIntentResponseV1.Size(m)
}
func (m *FillIntentResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_FillIntentResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_FillIntentResponseV1 proto.InternalMessageInfo

func (m *FillIntentResponseV1) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

func (m *FillIntentResponseV1) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *FillIntentResponseV1) GetCpPubKey() string {
	if m != nil {
		return m.CpPubKey
	}
	return ""
}

func (m *FillIntentResponseV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *FillIntentResponseV1) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *FillIntentResponseV1) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *FillIntentResponseV1) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *FillIntentResponseV1) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

func (m *FillIntentResponseV1) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *FillIntentResponseV1) GetCancelAt() string {
	if m != nil {
		return m.CancelAt
	}
	return ""
}

func (m *FillIntentResponseV1) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *FillIntentResponseV1) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *FillIntentResponseV1) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetIntentRequestV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserPubKey           string   `protobuf:"bytes,2,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	MakerAsset           string   `protobuf:"bytes,3,opt,name=makerAsset,proto3" json:"makerAsset,omitempty"`
	TakerAsset           string   `protobuf:"bytes,4,opt,name=takerAsset,proto3" json:"takerAsset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIntentRequestV1) Reset()         { *m = GetIntentRequestV1{} }
func (m *GetIntentRequestV1) String() string { return proto.CompactTextString(m) }
func (*GetIntentRequestV1) ProtoMessage()    {}
func (*GetIntentRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{9}
}

func (m *GetIntentRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIntentRequestV1.Unmarshal(m, b)
}
func (m *GetIntentRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIntentRequestV1.Marshal(b, m, deterministic)
}
func (m *GetIntentRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIntentRequestV1.Merge(m, src)
}
func (m *GetIntentRequestV1) XXX_Size() int {
	return xxx_messageInfo_GetIntentRequestV1.Size(m)
}
func (m *GetIntentRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIntentRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetIntentRequestV1 proto.InternalMessageInfo

func (m *GetIntentRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *GetIntentRequestV1) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *GetIntentRequestV1) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *GetIntentRequestV1) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

type GetIntentResponse struct {
	IntentId             string   `protobuf:"bytes,1,opt,name=intentId,proto3" json:"intentId,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserPubKey           string   `protobuf:"bytes,3,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	CpPubKey             string   `protobuf:"bytes,4,opt,name=cpPubKey,proto3" json:"cpPubKey,omitempty"`
	MakerAsset           string   `protobuf:"bytes,5,opt,name=makerAsset,proto3" json:"makerAsset,omitempty"`
	TakerAsset           string   `protobuf:"bytes,6,opt,name=takerAsset,proto3" json:"takerAsset,omitempty"`
	Quantity             float32  `protobuf:"fixed32,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	CancelAt             string   `protobuf:"bytes,10,opt,name=cancelAt,proto3" json:"cancelAt,omitempty"`
	Memo                 string   `protobuf:"bytes,11,opt,name=memo,proto3" json:"memo,omitempty"`
	Signature            string   `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	Status               string   `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIntentResponse) Reset()         { *m = GetIntentResponse{} }
func (m *GetIntentResponse) String() string { return proto.CompactTextString(m) }
func (*GetIntentResponse) ProtoMessage()    {}
func (*GetIntentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{10}
}

func (m *GetIntentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIntentResponse.Unmarshal(m, b)
}
func (m *GetIntentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIntentResponse.Marshal(b, m, deterministic)
}
func (m *GetIntentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIntentResponse.Merge(m, src)
}
func (m *GetIntentResponse) XXX_Size() int {
	return xxx_messageInfo_GetIntentResponse.Size(m)
}
func (m *GetIntentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIntentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIntentResponse proto.InternalMessageInfo

func (m *GetIntentResponse) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

func (m *GetIntentResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *GetIntentResponse) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *GetIntentResponse) GetCpPubKey() string {
	if m != nil {
		return m.CpPubKey
	}
	return ""
}

func (m *GetIntentResponse) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *GetIntentResponse) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

func (m *GetIntentResponse) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *GetIntentResponse) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetIntentResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetIntentResponse) GetCancelAt() string {
	if m != nil {
		return m.CancelAt
	}
	return ""
}

func (m *GetIntentResponse) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *GetIntentResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *GetIntentResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetIntentResponseV1 struct {
	Responses            []*GetIntentResponse `protobuf:"bytes,1,rep,name=Responses,proto3" json:"Responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetIntentResponseV1) Reset()         { *m = GetIntentResponseV1{} }
func (m *GetIntentResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetIntentResponseV1) ProtoMessage()    {}
func (*GetIntentResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{11}
}

func (m *GetIntentResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIntentResponseV1.Unmarshal(m, b)
}
func (m *GetIntentResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIntentResponseV1.Marshal(b, m, deterministic)
}
func (m *GetIntentResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIntentResponseV1.Merge(m, src)
}
func (m *GetIntentResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetIntentResponseV1.Size(m)
}
func (m *GetIntentResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIntentResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetIntentResponseV1 proto.InternalMessageInfo

func (m *GetIntentResponseV1) GetResponses() []*GetIntentResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type FillConfirmRequestV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	IntentId             string   `protobuf:"bytes,2,opt,name=intentId,proto3" json:"intentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FillConfirmRequestV1) Reset()         { *m = FillConfirmRequestV1{} }
func (m *FillConfirmRequestV1) String() string { return proto.CompactTextString(m) }
func (*FillConfirmRequestV1) ProtoMessage()    {}
func (*FillConfirmRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{12}
}

func (m *FillConfirmRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FillConfirmRequestV1.Unmarshal(m, b)
}
func (m *FillConfirmRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FillConfirmRequestV1.Marshal(b, m, deterministic)
}
func (m *FillConfirmRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FillConfirmRequestV1.Merge(m, src)
}
func (m *FillConfirmRequestV1) XXX_Size() int {
	return xxx_messageInfo_FillConfirmRequestV1.Size(m)
}
func (m *FillConfirmRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_FillConfirmRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_FillConfirmRequestV1 proto.InternalMessageInfo

func (m *FillConfirmRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *FillConfirmRequestV1) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

type FillConfirmResponseV1 struct {
	HTLCHash             string   `protobuf:"bytes,1,opt,name=HTLCHash,proto3" json:"HTLCHash,omitempty"`
	UserPubKey           string   `protobuf:"bytes,2,opt,name=UserPubKey,proto3" json:"UserPubKey,omitempty"`
	CpPubKey             string   `protobuf:"bytes,3,opt,name=CpPubKey,proto3" json:"CpPubKey,omitempty"`
	OrderId              string   `protobuf:"bytes,4,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	IntentId             string   `protobuf:"bytes,5,opt,name=IntentId,proto3" json:"IntentId,omitempty"`
	MakerChain           string   `protobuf:"bytes,6,opt,name=MakerChain,proto3" json:"MakerChain,omitempty"`
	TakerChain           string   `protobuf:"bytes,7,opt,name=TakerChain,proto3" json:"TakerChain,omitempty"`
	ChainId              string   `protobuf:"bytes,8,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	AssetId              string   `protobuf:"bytes,9,opt,name=AssetId,proto3" json:"AssetId,omitempty"`
	MakerAddress         string   `protobuf:"bytes,10,opt,name=MakerAddress,proto3" json:"MakerAddress,omitempty"`
	TakerAddress         string   `protobuf:"bytes,11,opt,name=TakerAddress,proto3" json:"TakerAddress,omitempty"`
	Quantity             float32  `protobuf:"fixed32,12,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Timeout              string   `protobuf:"bytes,13,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	PHash                string   `protobuf:"bytes,14,opt,name=pHash,proto3" json:"pHash,omitempty"`
	CreatedAt            string   `protobuf:"bytes,15,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Memo                 string   `protobuf:"bytes,16,opt,name=Memo,proto3" json:"Memo,omitempty"`
	Signature            string   `protobuf:"bytes,17,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Settled              bool     `protobuf:"varint,18,opt,name=Settled,proto3" json:"Settled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FillConfirmResponseV1) Reset()         { *m = FillConfirmResponseV1{} }
func (m *FillConfirmResponseV1) String() string { return proto.CompactTextString(m) }
func (*FillConfirmResponseV1) ProtoMessage()    {}
func (*FillConfirmResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{13}
}

func (m *FillConfirmResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FillConfirmResponseV1.Unmarshal(m, b)
}
func (m *FillConfirmResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FillConfirmResponseV1.Marshal(b, m, deterministic)
}
func (m *FillConfirmResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FillConfirmResponseV1.Merge(m, src)
}
func (m *FillConfirmResponseV1) XXX_Size() int {
	return xxx_messageInfo_FillConfirmResponseV1.Size(m)
}
func (m *FillConfirmResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_FillConfirmResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_FillConfirmResponseV1 proto.InternalMessageInfo

func (m *FillConfirmResponseV1) GetHTLCHash() string {
	if m != nil {
		return m.HTLCHash
	}
	return ""
}

func (m *FillConfirmResponseV1) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *FillConfirmResponseV1) GetCpPubKey() string {
	if m != nil {
		return m.CpPubKey
	}
	return ""
}

func (m *FillConfirmResponseV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *FillConfirmResponseV1) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

func (m *FillConfirmResponseV1) GetMakerChain() string {
	if m != nil {
		return m.MakerChain
	}
	return ""
}

func (m *FillConfirmResponseV1) GetTakerChain() string {
	if m != nil {
		return m.TakerChain
	}
	return ""
}

func (m *FillConfirmResponseV1) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *FillConfirmResponseV1) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *FillConfirmResponseV1) GetMakerAddress() string {
	if m != nil {
		return m.MakerAddress
	}
	return ""
}

func (m *FillConfirmResponseV1) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *FillConfirmResponseV1) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *FillConfirmResponseV1) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *FillConfirmResponseV1) GetPHash() string {
	if m != nil {
		return m.PHash
	}
	return ""
}

func (m *FillConfirmResponseV1) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *FillConfirmResponseV1) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *FillConfirmResponseV1) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *FillConfirmResponseV1) GetSettled() bool {
	if m != nil {
		return m.Settled
	}
	return false
}

type CancelIntentRequestV1 struct {
	IntentId             string   `protobuf:"bytes,1,opt,name=intentId,proto3" json:"intentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelIntentRequestV1) Reset()         { *m = CancelIntentRequestV1{} }
func (m *CancelIntentRequestV1) String() string { return proto.CompactTextString(m) }
func (*CancelIntentRequestV1) ProtoMessage()    {}
func (*CancelIntentRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{14}
}

func (m *CancelIntentRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelIntentRequestV1.Unmarshal(m, b)
}
func (m *CancelIntentRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelIntentRequestV1.Marshal(b, m, deterministic)
}
func (m *CancelIntentRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelIntentRequestV1.Merge(m, src)
}
func (m *CancelIntentRequestV1) XXX_Size() int {
	return xxx_messageInfo_CancelIntentRequestV1.Size(m)
}
func (m *CancelIntentRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelIntentRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CancelIntentRequestV1 proto.InternalMessageInfo

func (m *CancelIntentRequestV1) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

type CancelIntentResponseV1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelIntentResponseV1) Reset()         { *m = CancelIntentResponseV1{} }
func (m *CancelIntentResponseV1) String() string { return proto.CompactTextString(m) }
func (*CancelIntentResponseV1) ProtoMessage()    {}
func (*CancelIntentResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{15}
}

func (m *CancelIntentResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelIntentResponseV1.Unmarshal(m, b)
}
func (m *CancelIntentResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelIntentResponseV1.Marshal(b, m, deterministic)
}
func (m *CancelIntentResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelIntentResponseV1.Merge(m, src)
}
func (m *CancelIntentResponseV1) XXX_Size() int {
	return xxx_messageInfo_CancelIntentResponseV1.Size(m)
}
func (m *CancelIntentResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelIntentResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CancelIntentResponseV1 proto.InternalMessageInfo

type CancelOrderRequestV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderRequestV1) Reset()         { *m = CancelOrderRequestV1{} }
func (m *CancelOrderRequestV1) String() string { return proto.CompactTextString(m) }
func (*CancelOrderRequestV1) ProtoMessage()    {}
func (*CancelOrderRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{16}
}

func (m *CancelOrderRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderRequestV1.Unmarshal(m, b)
}
func (m *CancelOrderRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderRequestV1.Marshal(b, m, deterministic)
}
func (m *CancelOrderRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderRequestV1.Merge(m, src)
}
func (m *CancelOrderRequestV1) XXX_Size() int {
	return xxx_messageInfo_CancelOrderRequestV1.Size(m)
}
func (m *CancelOrderRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderRequestV1 proto.InternalMessageInfo

func (m *CancelOrderRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type CancelOrderResponseV1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderResponseV1) Reset()         { *m = CancelOrderResponseV1{} }
func (m *CancelOrderResponseV1) String() string { return proto.CompactTextString(m) }
func (*CancelOrderResponseV1) ProtoMessage()    {}
func (*CancelOrderResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{17}
}

func (m *CancelOrderResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderResponseV1.Unmarshal(m, b)
}
func (m *CancelOrderResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderResponseV1.Marshal(b, m, deterministic)
}
func (m *CancelOrderResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderResponseV1.Merge(m, src)
}
func (m *CancelOrderResponseV1) XXX_Size() int {
	return xxx_messageInfo_CancelOrderResponseV1.Size(m)
}
func (m *CancelOrderResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderResponseV1 proto.InternalMessageInfo

type GetBalancesRequestV1 struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	AssetId              string   `protobuf:"bytes,2,opt,name=AssetId,proto3" json:"AssetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalancesRequestV1) Reset()         { *m = GetBalancesRequestV1{} }
func (m *GetBalancesRequestV1) String() string { return proto.CompactTextString(m) }
func (*GetBalancesRequestV1) ProtoMessage()    {}
func (*GetBalancesRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{18}
}

func (m *GetBalancesRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalancesRequestV1.Unmarshal(m, b)
}
func (m *GetBalancesRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalancesRequestV1.Marshal(b, m, deterministic)
}
func (m *GetBalancesRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalancesRequestV1.Merge(m, src)
}
func (m *GetBalancesRequestV1) XXX_Size() int {
	return xxx_messageInfo_GetBalancesRequestV1.Size(m)
}
func (m *GetBalancesRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalancesRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalancesRequestV1 proto.InternalMessageInfo

func (m *GetBalancesRequestV1) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *GetBalancesRequestV1) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

type GetBalancesResponse struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	AssetId              string   `protobuf:"bytes,2,opt,name=AssetId,proto3" json:"AssetId,omitempty"`
	Quantity             string   `protobuf:"bytes,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	AddressQuantity      string   `protobuf:"bytes,5,opt,name=AddressQuantity,proto3" json:"AddressQuantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalancesResponse) Reset()         { *m = GetBalancesResponse{} }
func (m *GetBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalancesResponse) ProtoMessage()    {}
func (*GetBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{19}
}

func (m *GetBalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalancesResponse.Unmarshal(m, b)
}
func (m *GetBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalancesResponse.Marshal(b, m, deterministic)
}
func (m *GetBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalancesResponse.Merge(m, src)
}
func (m *GetBalancesResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalancesResponse.Size(m)
}
func (m *GetBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalancesResponse proto.InternalMessageInfo

func (m *GetBalancesResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *GetBalancesResponse) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *GetBalancesResponse) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *GetBalancesResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetBalancesResponse) GetAddressQuantity() string {
	if m != nil {
		return m.AddressQuantity
	}
	return ""
}

type GetBalancesResponseV1 struct {
	Responses            []*GetBalancesResponse `protobuf:"bytes,1,rep,name=Responses,proto3" json:"Responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetBalancesResponseV1) Reset()         { *m = GetBalancesResponseV1{} }
func (m *GetBalancesResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetBalancesResponseV1) ProtoMessage()    {}
func (*GetBalancesResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{20}
}

func (m *GetBalancesResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalancesResponseV1.Unmarshal(m, b)
}
func (m *GetBalancesResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalancesResponseV1.Marshal(b, m, deterministic)
}
func (m *GetBalancesResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalancesResponseV1.Merge(m, src)
}
func (m *GetBalancesResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetBalancesResponseV1.Size(m)
}
func (m *GetBalancesResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalancesResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalancesResponseV1 proto.InternalMessageInfo

func (m *GetBalancesResponseV1) GetResponses() []*GetBalancesResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type GetFillRequestV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFillRequestV1) Reset()         { *m = GetFillRequestV1{} }
func (m *GetFillRequestV1) String() string { return proto.CompactTextString(m) }
func (*GetFillRequestV1) ProtoMessage()    {}
func (*GetFillRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{21}
}

func (m *GetFillRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFillRequestV1.Unmarshal(m, b)
}
func (m *GetFillRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFillRequestV1.Marshal(b, m, deterministic)
}
func (m *GetFillRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFillRequestV1.Merge(m, src)
}
func (m *GetFillRequestV1) XXX_Size() int {
	return xxx_messageInfo_GetFillRequestV1.Size(m)
}
func (m *GetFillRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFillRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetFillRequestV1 proto.InternalMessageInfo

func (m *GetFillRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type GetFillResponse struct {
	HTLCHash             string   `protobuf:"bytes,1,opt,name=HTLCHash,proto3" json:"HTLCHash,omitempty"`
	MakerAddress         string   `protobuf:"bytes,2,opt,name=MakerAddress,proto3" json:"MakerAddress,omitempty"`
	TakerAddress         string   `protobuf:"bytes,3,opt,name=TakerAddress,proto3" json:"TakerAddress,omitempty"`
	Quantity             float32  `protobuf:"fixed32,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Timeout              int32    `protobuf:"varint,5,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	PHash                string   `protobuf:"bytes,6,opt,name=pHash,proto3" json:"pHash,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Memo                 string   `protobuf:"bytes,8,opt,name=Memo,proto3" json:"Memo,omitempty"`
	Signature            string   `protobuf:"bytes,9,opt,name=Signature,proto3" json:"Signature,omitempty"`
	ChainId              string   `protobuf:"bytes,10,opt,name=chainId,proto3" json:"chainId,omitempty"`
	AssetId              string   `protobuf:"bytes,11,opt,name=assetId,proto3" json:"assetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFillResponse) Reset()         { *m = GetFillResponse{} }
func (m *GetFillResponse) String() string { return proto.CompactTextString(m) }
func (*GetFillResponse) ProtoMessage()    {}
func (*GetFillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{22}
}

func (m *GetFillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFillResponse.Unmarshal(m, b)
}
func (m *GetFillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFillResponse.Marshal(b, m, deterministic)
}
func (m *GetFillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFillResponse.Merge(m, src)
}
func (m *GetFillResponse) XXX_Size() int {
	return xxx_messageInfo_GetFillResponse.Size(m)
}
func (m *GetFillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFillResponse proto.InternalMessageInfo

func (m *GetFillResponse) GetHTLCHash() string {
	if m != nil {
		return m.HTLCHash
	}
	return ""
}

func (m *GetFillResponse) GetMakerAddress() string {
	if m != nil {
		return m.MakerAddress
	}
	return ""
}

func (m *GetFillResponse) GetTakerAddress() string {
	if m != nil {
		return m.TakerAddress
	}
	return ""
}

func (m *GetFillResponse) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *GetFillResponse) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *GetFillResponse) GetPHash() string {
	if m != nil {
		return m.PHash
	}
	return ""
}

func (m *GetFillResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetFillResponse) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *GetFillResponse) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *GetFillResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *GetFillResponse) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

type GetFillResponseV1 struct {
	UserPubKey           string             `protobuf:"bytes,1,opt,name=UserPubKey,proto3" json:"UserPubKey,omitempty"`
	CpPubKey             string             `protobuf:"bytes,2,opt,name=CpPubKey,proto3" json:"CpPubKey,omitempty"`
	OrderId              string             `protobuf:"bytes,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	IntentId             string             `protobuf:"bytes,4,opt,name=IntentId,proto3" json:"IntentId,omitempty"`
	Makerchain           string             `protobuf:"bytes,5,opt,name=makerchain,proto3" json:"makerchain,omitempty"`
	Takerchain           string             `protobuf:"bytes,6,opt,name=takerchain,proto3" json:"takerchain,omitempty"`
	Responses            []*GetFillResponse `protobuf:"bytes,7,rep,name=Responses,proto3" json:"Responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetFillResponseV1) Reset()         { *m = GetFillResponseV1{} }
func (m *GetFillResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetFillResponseV1) ProtoMessage()    {}
func (*GetFillResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{23}
}

func (m *GetFillResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFillResponseV1.Unmarshal(m, b)
}
func (m *GetFillResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFillResponseV1.Marshal(b, m, deterministic)
}
func (m *GetFillResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFillResponseV1.Merge(m, src)
}
func (m *GetFillResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetFillResponseV1.Size(m)
}
func (m *GetFillResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFillResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetFillResponseV1 proto.InternalMessageInfo

func (m *GetFillResponseV1) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *GetFillResponseV1) GetCpPubKey() string {
	if m != nil {
		return m.CpPubKey
	}
	return ""
}

func (m *GetFillResponseV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *GetFillResponseV1) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

func (m *GetFillResponseV1) GetMakerchain() string {
	if m != nil {
		return m.Makerchain
	}
	return ""
}

func (m *GetFillResponseV1) GetTakerchain() string {
	if m != nil {
		return m.Takerchain
	}
	return ""
}

func (m *GetFillResponseV1) GetResponses() []*GetFillResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type GetNodeInfoRequestV1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeInfoRequestV1) Reset()         { *m = GetNodeInfoRequestV1{} }
func (m *GetNodeInfoRequestV1) String() string { return proto.CompactTextString(m) }
func (*GetNodeInfoRequestV1) ProtoMessage()    {}
func (*GetNodeInfoRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{24}
}

func (m *GetNodeInfoRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeInfoRequestV1.Unmarshal(m, b)
}
func (m *GetNodeInfoRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeInfoRequestV1.Marshal(b, m, deterministic)
}
func (m *GetNodeInfoRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeInfoRequestV1.Merge(m, src)
}
func (m *GetNodeInfoRequestV1) XXX_Size() int {
	return xxx_messageInfo_GetNodeInfoRequestV1.Size(m)
}
func (m *GetNodeInfoRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeInfoRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeInfoRequestV1 proto.InternalMessageInfo

type GetNodeInfoResponseV1 struct {
	UserPubKey           string   `protobuf:"bytes,1,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeInfoResponseV1) Reset()         { *m = GetNodeInfoResponseV1{} }
func (m *GetNodeInfoResponseV1) String() string { return proto.CompactTextString(m) }
func (*GetNodeInfoResponseV1) ProtoMessage()    {}
func (*GetNodeInfoResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{25}
}

func (m *GetNodeInfoResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeInfoResponseV1.Unmarshal(m, b)
}
func (m *GetNodeInfoResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeInfoResponseV1.Marshal(b, m, deterministic)
}
func (m *GetNodeInfoResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeInfoResponseV1.Merge(m, src)
}
func (m *GetNodeInfoResponseV1) XXX_Size() int {
	return xxx_messageInfo_GetNodeInfoResponseV1.Size(m)
}
func (m *GetNodeInfoResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeInfoResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeInfoResponseV1 proto.InternalMessageInfo

func (m *GetNodeInfoResponseV1) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func init() {
	proto.RegisterType((*ConnectPeerRequestV1)(nil), "pb.ConnectPeerRequestV1")
	proto.RegisterType((*ConnectPeerResponseV1)(nil), "pb.ConnectPeerResponseV1")
	proto.RegisterType((*PostOrderRequestV1)(nil), "pb.PostOrderRequestV1")
	proto.RegisterType((*PostOrderResponseV1)(nil), "pb.PostOrderResponseV1")
	proto.RegisterType((*GetOrderRequestV1)(nil), "pb.GetOrderRequestV1")
	proto.RegisterType((*GetOrderResponse)(nil), "pb.GetOrderResponse")
	proto.RegisterType((*GetOrderResponseV1)(nil), "pb.GetOrderResponseV1")
	proto.RegisterType((*FillIntentRequestV1)(nil), "pb.FillIntentRequestV1")
	proto.RegisterType((*FillIntentResponseV1)(nil), "pb.FillIntentResponseV1")
	proto.RegisterType((*GetIntentRequestV1)(nil), "pb.GetIntentRequestV1")
	proto.RegisterType((*GetIntentResponse)(nil), "pb.GetIntentResponse")
	proto.RegisterType((*GetIntentResponseV1)(nil), "pb.GetIntentResponseV1")
	proto.RegisterType((*FillConfirmRequestV1)(nil), "pb.FillConfirmRequestV1")
	proto.RegisterType((*FillConfirmResponseV1)(nil), "pb.FillConfirmResponseV1")
	proto.RegisterType((*CancelIntentRequestV1)(nil), "pb.CancelIntentRequestV1")
	proto.RegisterType((*CancelIntentResponseV1)(nil), "pb.CancelIntentResponseV1")
	proto.RegisterType((*CancelOrderRequestV1)(nil), "pb.CancelOrderRequestV1")
	proto.RegisterType((*CancelOrderResponseV1)(nil), "pb.CancelOrderResponseV1")
	proto.RegisterType((*GetBalancesRequestV1)(nil), "pb.GetBalancesRequestV1")
	proto.RegisterType((*GetBalancesResponse)(nil), "pb.GetBalancesResponse")
	proto.RegisterType((*GetBalancesResponseV1)(nil), "pb.GetBalancesResponseV1")
	proto.RegisterType((*GetFillRequestV1)(nil), "pb.GetFillRequestV1")
	proto.RegisterType((*GetFillResponse)(nil), "pb.GetFillResponse")
	proto.RegisterType((*GetFillResponseV1)(nil), "pb.GetFillResponseV1")
	proto.RegisterType((*GetNodeInfoRequestV1)(nil), "pb.GetNodeInfoRequestV1")
	proto.RegisterType((*GetNodeInfoResponseV1)(nil), "pb.GetNodeInfoResponseV1")
}

func init() { proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c) }

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 1316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xcb, 0x6e, 0x23, 0x45,
	0x14, 0x55, 0xb7, 0xed, 0xd8, 0x2e, 0x3b, 0x93, 0xa4, 0x62, 0x3b, 0x1d, 0x33, 0x42, 0x51, 0xad,
	0x2c, 0x84, 0x12, 0x9c, 0x08, 0x21, 0xb1, 0x0b, 0x96, 0x98, 0x78, 0x66, 0xf2, 0x18, 0xe7, 0x21,
	0x21, 0x10, 0x52, 0xc7, 0xae, 0xc9, 0xb4, 0xc6, 0xee, 0xf6, 0x74, 0x97, 0x19, 0x8d, 0xd8, 0xb1,
	0x87, 0x0d, 0x0b, 0xbe, 0x81, 0x05, 0x5b, 0x3e, 0x00, 0x89, 0x2f, 0xe0, 0x17, 0xf8, 0x08, 0xa4,
	0x91, 0x10, 0xaa, 0x77, 0x55, 0x3f, 0x1c, 0xb3, 0x18, 0x21, 0xb1, 0xf3, 0x7d, 0xf4, 0xad, 0x5b,
	0xf7, 0x9e, 0x7b, 0xaa, 0xca, 0xa0, 0xe1, 0x4f, 0x66, 0x41, 0xb8, 0x3f, 0x8f, 0x23, 0x12, 0x41,
	0x77, 0x7e, 0xdb, 0x7d, 0x78, 0x17, 0x45, 0x77, 0x53, 0x7c, 0xe0, 0xcf, 0x83, 0x03, 0x3f, 0x0c,
	0x23, 0xe2, 0x93, 0x20, 0x0a, 0x13, 0xee, 0x81, 0xf6, 0x41, 0x6b, 0x10, 0x85, 0x21, 0x1e, 0x93,
	0x0b, 0x8c, 0xe3, 0x11, 0x7e, 0xb5, 0xc0, 0x09, 0xb9, 0xe9, 0xc3, 0x0e, 0x58, 0x9b, 0x63, 0x1c,
	0x0f, 0x27, 0x9e, 0xb3, 0xe7, 0xf4, 0xea, 0x23, 0x21, 0xa1, 0x03, 0xd0, 0xb6, 0xfc, 0x93, 0x79,
	0x14, 0x26, 0x78, 0xc9, 0x07, 0xbf, 0x3a, 0x00, 0x5e, 0x44, 0x09, 0x39, 0x8f, 0x27, 0x66, 0xfc,
	0xf7, 0x01, 0x98, 0xf9, 0x2f, 0x71, 0x7c, 0x9c, 0x24, 0x98, 0x88, 0x4f, 0x0c, 0x0d, 0xb5, 0x13,
	0x6d, 0x77, 0xb9, 0x5d, 0x6b, 0x60, 0x17, 0xd4, 0x5e, 0x2d, 0xfc, 0x90, 0x04, 0xe4, 0x8d, 0x57,
	0xda, 0x73, 0x7a, 0xee, 0x48, 0xc9, 0xb0, 0x05, 0x2a, 0xf3, 0x38, 0x18, 0x63, 0xaf, 0xcc, 0x0c,
	0x5c, 0xa0, 0x5f, 0x8c, 0xfd, 0x70, 0x8c, 0xa7, 0xc7, 0xc4, 0xab, 0xb0, 0x78, 0x4a, 0x86, 0x10,
	0x94, 0x67, 0x78, 0x16, 0x79, 0x55, 0xa6, 0x67, 0xbf, 0xd1, 0x2f, 0x2e, 0xd8, 0x36, 0x12, 0x57,
	0x1b, 0xf5, 0x40, 0x35, 0xa2, 0x2a, 0xb5, 0x53, 0x29, 0xd2, 0x9c, 0x17, 0x09, 0x8e, 0x2f, 0x16,
	0xb7, 0x2f, 0xf1, 0x1b, 0x99, 0xb3, 0xd6, 0xa4, 0xf6, 0x5c, 0xba, 0x67, 0xcf, 0xe5, 0xa5, 0x7b,
	0xae, 0x14, 0xed, 0x79, 0xad, 0x68, 0xcf, 0xd5, 0xd4, 0x9e, 0x1f, 0x82, 0xfa, 0x38, 0xc6, 0x3e,
	0xc1, 0x93, 0x63, 0xe2, 0xd5, 0x98, 0x51, 0x2b, 0x54, 0x45, 0xea, 0xba, 0x22, 0xf4, 0x8b, 0x24,
	0xb8, 0x0b, 0x7d, 0xb2, 0x88, 0xb1, 0x07, 0xf6, 0x9c, 0x5e, 0x73, 0xa4, 0x15, 0xe8, 0x7b, 0x07,
	0x6c, 0x3d, 0xc2, 0xe9, 0x3e, 0xff, 0x67, 0xd5, 0x42, 0xbf, 0xb9, 0x60, 0x53, 0xe7, 0xc3, 0xdb,
	0xb7, 0x52, 0x3a, 0x4f, 0x32, 0xe9, 0x3c, 0xf9, 0xbf, 0x37, 0x8f, 0x4e, 0x6f, 0x42, 0x7c, 0xb2,
	0x48, 0xbc, 0x06, 0x9f, 0x5e, 0x2e, 0xa1, 0x13, 0x00, 0xd3, 0x35, 0xbc, 0xe9, 0xc3, 0x43, 0x50,
	0x97, 0x52, 0xe2, 0x39, 0x7b, 0xa5, 0x5e, 0xe3, 0xb0, 0xb5, 0x3f, 0xbf, 0xdd, 0x4f, 0xbb, 0x8e,
	0xb4, 0x1b, 0xfa, 0x16, 0x6c, 0x7f, 0x1e, 0x4c, 0xa7, 0xc3, 0x90, 0xe0, 0x90, 0xac, 0x82, 0x0f,
	0xb3, 0x60, 0x6e, 0xaa, 0x60, 0x66, 0x69, 0x4a, 0x05, 0xb3, 0x5c, 0x36, 0x66, 0xf9, 0x6f, 0x17,
	0xb4, 0xcc, 0xd5, 0xd5, 0x4e, 0xba, 0xa0, 0x16, 0x30, 0x9d, 0x5a, 0x5f, 0xc9, 0xf7, 0x22, 0x82,
	0x26, 0x31, 0x17, 0x56, 0x99, 0x84, 0x90, 0xcd, 0x6d, 0x95, 0x8b, 0xb7, 0xb5, 0x1a, 0x0e, 0x6c,
	0xe4, 0x55, 0xef, 0x41, 0x5e, 0x2d, 0x83, 0x3c, 0x0b, 0x2b, 0xf5, 0x34, 0x56, 0xcc, 0x52, 0x82,
	0x82, 0x52, 0x36, 0x8a, 0x70, 0xd4, 0x2c, 0xc6, 0xd1, 0xba, 0x85, 0xa3, 0x1f, 0x1c, 0x06, 0xa4,
	0xd5, 0xbb, 0xff, 0x8e, 0xc7, 0x11, 0xbd, 0x75, 0x19, 0x5b, 0xd9, 0x80, 0x58, 0x0a, 0x07, 0x23,
	0x57, 0x77, 0x59, 0xae, 0xa5, 0xa5, 0x40, 0x29, 0xa7, 0x80, 0x62, 0xef, 0xa3, 0x72, 0xcf, 0x3e,
	0xd6, 0x96, 0xd2, 0x4a, 0xb5, 0x08, 0x4e, 0x35, 0x13, 0x4e, 0xef, 0x18, 0x0e, 0xf5, 0x55, 0xe0,
	0xf0, 0x18, 0x6c, 0x67, 0x8a, 0x7f, 0xd3, 0x87, 0x47, 0x59, 0x5e, 0x69, 0x0b, 0x5e, 0xb1, 0x7d,
	0x4d, 0x62, 0x79, 0xca, 0x47, 0x7b, 0x10, 0x85, 0xcf, 0x83, 0x78, 0xb6, 0x22, 0xb3, 0xa8, 0x2e,
	0xbb, 0x76, 0x97, 0xd1, 0x4f, 0x65, 0xd0, 0xb6, 0xc2, 0x99, 0x54, 0x71, 0x72, 0xf5, 0x74, 0x70,
	0xe2, 0x27, 0x2f, 0x24, 0x36, 0xa4, 0x4c, 0xbb, 0x74, 0x9d, 0x41, 0xeb, 0xb5, 0x85, 0x80, 0x41,
	0x8a, 0x2a, 0x06, 0x06, 0x55, 0x9c, 0xdb, 0x54, 0x71, 0xae, 0xf3, 0x1c, 0xca, 0x3c, 0xc5, 0x8d,
	0x65, 0x68, 0x90, 0xd3, 0x29, 0x45, 0xc1, 0xe0, 0x85, 0x1f, 0x84, 0x12, 0x17, 0x5a, 0x43, 0xed,
	0x57, 0xda, 0x2e, 0x48, 0x43, 0x6b, 0xe8, 0xaa, 0xec, 0xc7, 0x70, 0x22, 0x18, 0x43, 0x8a, 0xd4,
	0xc2, 0xa0, 0x35, 0x9c, 0x08, 0x74, 0x48, 0x11, 0x22, 0xd0, 0x64, 0x2b, 0x1c, 0x4f, 0x26, 0x31,
	0x4e, 0x12, 0x81, 0x0f, 0x4b, 0x47, 0x7d, 0xae, 0x4c, 0x1f, 0x8e, 0x15, 0x4b, 0x47, 0xf7, 0xf5,
	0x4c, 0x62, 0xb6, 0xc9, 0x31, 0x2b, 0x65, 0xba, 0xfa, 0x55, 0x30, 0xc3, 0xd1, 0x82, 0x08, 0xc8,
	0x48, 0x91, 0xa1, 0x99, 0x15, 0xff, 0x01, 0xd3, 0x73, 0x81, 0xe2, 0x6f, 0xa0, 0xd0, 0xbc, 0xc1,
	0xf1, 0x37, 0x30, 0x0f, 0xc2, 0x53, 0x8a, 0xd8, 0x4d, 0x8e, 0xd8, 0x53, 0x81, 0xd8, 0x4b, 0x85,
	0xd8, 0x2d, 0xfe, 0x85, 0x52, 0xd0, 0xf5, 0x2f, 0x31, 0x21, 0x53, 0x3c, 0xf1, 0xe0, 0x9e, 0xd3,
	0xab, 0x8d, 0xa4, 0x88, 0x8e, 0x40, 0x7b, 0xc0, 0x26, 0x21, 0x4d, 0x62, 0x4b, 0x48, 0x03, 0x79,
	0xa0, 0x63, 0x7f, 0x24, 0xe1, 0x84, 0x3e, 0x02, 0x2d, 0x6e, 0x59, 0xf5, 0xc2, 0x84, 0x76, 0x64,
	0x02, 0xa9, 0xe3, 0x18, 0x3d, 0x06, 0xad, 0x47, 0x98, 0x7c, 0xe6, 0x4f, 0xa9, 0x35, 0xb1, 0x42,
	0xc9, 0x1e, 0x3b, 0x85, 0x3d, 0x76, 0xad, 0x1e, 0xa3, 0x9f, 0x1d, 0x36, 0x9a, 0x3a, 0x98, 0xbe,
	0x38, 0xfd, 0xdb, 0x58, 0x56, 0x9f, 0x05, 0xea, 0xcd, 0x3e, 0x4b, 0x88, 0x08, 0xd4, 0x4b, 0x74,
	0xf4, 0xc0, 0x86, 0xf8, 0xf9, 0xcc, 0x3c, 0x27, 0xeb, 0xa3, 0xb4, 0x1a, 0x9d, 0x81, 0x76, 0x4e,
	0xaa, 0x37, 0x7d, 0xf8, 0x71, 0x96, 0x47, 0x76, 0x04, 0x8f, 0xa4, 0xbd, 0x4d, 0x26, 0xf9, 0x90,
	0x5d, 0x18, 0xe9, 0xf4, 0x5b, 0x35, 0x3c, 0xb7, 0xdb, 0x21, 0x44, 0xf4, 0xbb, 0x0b, 0x36, 0x94,
	0xbb, 0x3e, 0x3f, 0x0a, 0x39, 0x22, 0x3d, 0x3d, 0xee, 0x0a, 0xd3, 0x53, 0xba, 0x67, 0x7a, 0xca,
	0xc5, 0xd3, 0x43, 0x6b, 0x56, 0xc9, 0x99, 0x9e, 0xb5, 0xc2, 0xe9, 0xa9, 0x16, 0x4d, 0x4f, 0xad,
	0x68, 0x7a, 0xea, 0x39, 0xd3, 0x33, 0x16, 0x28, 0xe1, 0xe4, 0x20, 0x45, 0x6a, 0xf1, 0x05, 0x4a,
	0x38, 0x25, 0x48, 0x11, 0xfd, 0xc5, 0xdf, 0x0d, 0x66, 0x1d, 0xf9, 0xfb, 0xd0, 0x60, 0x54, 0x67,
	0x29, 0xa3, 0xba, 0xc5, 0x8c, 0x5a, 0x2a, 0x66, 0xd4, 0x72, 0x96, 0x51, 0xd9, 0xb9, 0xcb, 0x32,
	0xb6, 0x4e, 0xe2, 0xb1, 0x64, 0x54, 0xa2, 0xed, 0xe6, 0x49, 0xcc, 0xed, 0x7d, 0x13, 0x74, 0x55,
	0x06, 0xba, 0x6d, 0x01, 0x3a, 0x73, 0x6f, 0x26, 0xe0, 0x3a, 0x6c, 0x70, 0xcf, 0xa2, 0x09, 0x1e,
	0x86, 0xcf, 0x23, 0x05, 0x3a, 0xf4, 0x09, 0x03, 0xb6, 0xd6, 0x9b, 0x55, 0x59, 0x64, 0xaa, 0xa2,
	0x35, 0x87, 0x6f, 0xab, 0xa0, 0x72, 0x4c, 0xdf, 0xff, 0xf0, 0x6b, 0xd0, 0x30, 0xde, 0xe9, 0xd0,
	0xa3, 0x99, 0xe4, 0x3d, 0xf4, 0xbb, 0xbb, 0x19, 0x8b, 0xe2, 0x95, 0xee, 0x77, 0x7f, 0xfc, 0xf9,
	0xa3, 0xdb, 0x42, 0x1b, 0x07, 0xdf, 0xf4, 0x0f, 0x0c, 0x97, 0x4f, 0x9d, 0x0f, 0xe0, 0x35, 0xa8,
	0xab, 0xc7, 0x31, 0xec, 0xd0, 0x18, 0xd9, 0x47, 0x7e, 0x77, 0x27, 0xa5, 0x57, 0x91, 0x77, 0x58,
	0xe4, 0x2d, 0xd4, 0xa4, 0x91, 0xcf, 0xf0, 0x6b, 0x66, 0xa7, 0x61, 0x2f, 0x41, 0x4d, 0x3e, 0x22,
	0x60, 0xdb, 0x7e, 0x52, 0xc8, 0xa0, 0x9d, 0xbc, 0x97, 0xc6, 0x4d, 0x1f, 0x79, 0x2c, 0x26, 0x44,
	0xeb, 0x34, 0xa6, 0xb4, 0x27, 0x34, 0xe8, 0x17, 0x00, 0xe8, 0xcb, 0x3f, 0x64, 0x49, 0xe5, 0x3c,
	0x45, 0xba, 0x5e, 0xda, 0x90, 0x1f, 0xfa, 0x0c, 0xbf, 0xe6, 0x0e, 0x34, 0xf4, 0x97, 0x60, 0x5d,
	0xf4, 0x57, 0x44, 0xef, 0xa4, 0xee, 0x2b, 0x56, 0x29, 0x72, 0xee, 0x3c, 0x68, 0x97, 0xc5, 0xde,
	0x46, 0x0f, 0x44, 0xda, 0xdc, 0x81, 0xe5, 0xfd, 0x15, 0x68, 0x18, 0x57, 0x11, 0xa8, 0xf2, 0x4b,
	0x5f, 0x75, 0x78, 0x0f, 0x73, 0x6f, 0x2d, 0x76, 0xea, 0xd4, 0x45, 0x95, 0xfa, 0x16, 0x34, 0xcd,
	0xa3, 0x09, 0x72, 0x20, 0xe4, 0x9d, 0x70, 0xdd, 0x6e, 0xd6, 0xa4, 0x16, 0x78, 0x8f, 0x2d, 0xd0,
	0x46, 0x9b, 0x0c, 0x24, 0x86, 0x0f, 0x5d, 0x83, 0xa2, 0x50, 0x1f, 0x59, 0x02, 0x85, 0x39, 0xa7,
	0x5e, 0x77, 0x37, 0x63, 0x29, 0x40, 0xa1, 0x76, 0x11, 0xf1, 0x0d, 0x4e, 0xe7, 0xf1, 0xf3, 0x8e,
	0x42, 0x1e, 0x3f, 0xf7, 0xb0, 0xb0, 0xe3, 0x1b, 0x2e, 0x34, 0xfe, 0x39, 0xa8, 0x8a, 0xf6, 0xc2,
	0x96, 0x35, 0xcb, 0x32, 0x6e, 0x3b, 0x67, 0xc2, 0xd3, 0xf8, 0x16, 0xe6, 0x84, 0xe3, 0xa5, 0x61,
	0x4c, 0xb6, 0x4a, 0x38, 0x43, 0x01, 0x2a, 0xe1, 0x2c, 0x09, 0xc8, 0xe0, 0x50, 0x26, 0x2c, 0x5d,
	0x6e, 0xd7, 0xd8, 0x5f, 0x7a, 0x47, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x97, 0xed, 0xcd, 0x2f,
	0x03, 0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminClient interface {
	ConnectPeer(ctx context.Context, in *ConnectPeerRequestV1, opts ...grpc.CallOption) (*ConnectPeerResponseV1, error)
	PostOrder(ctx context.Context, in *PostOrderRequestV1, opts ...grpc.CallOption) (*PostOrderResponseV1, error)
	GetOrder(ctx context.Context, in *GetOrderRequestV1, opts ...grpc.CallOption) (*GetOrderResponseV1, error)
	FillIntent(ctx context.Context, in *FillIntentRequestV1, opts ...grpc.CallOption) (*FillIntentResponseV1, error)
	GetFillIntent(ctx context.Context, in *GetIntentRequestV1, opts ...grpc.CallOption) (*GetIntentResponseV1, error)
	FillConfirm(ctx context.Context, in *FillConfirmRequestV1, opts ...grpc.CallOption) (*FillConfirmResponseV1, error)
	CancelIntent(ctx context.Context, in *CancelIntentRequestV1, opts ...grpc.CallOption) (*CancelIntentResponseV1, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequestV1, opts ...grpc.CallOption) (*CancelOrderResponseV1, error)
	GetBalances(ctx context.Context, in *GetBalancesRequestV1, opts ...grpc.CallOption) (*GetBalancesResponseV1, error)
	GetFill(ctx context.Context, in *GetFillRequestV1, opts ...grpc.CallOption) (*GetFillResponseV1, error)
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequestV1, opts ...grpc.CallOption) (*GetNodeInfoResponseV1, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ConnectPeer(ctx context.Context, in *ConnectPeerRequestV1, opts ...grpc.CallOption) (*ConnectPeerResponseV1, error) {
	out := new(ConnectPeerResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/ConnectPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) PostOrder(ctx context.Context, in *PostOrderRequestV1, opts ...grpc.CallOption) (*PostOrderResponseV1, error) {
	out := new(PostOrderResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/PostOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetOrder(ctx context.Context, in *GetOrderRequestV1, opts ...grpc.CallOption) (*GetOrderResponseV1, error) {
	out := new(GetOrderResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) FillIntent(ctx context.Context, in *FillIntentRequestV1, opts ...grpc.CallOption) (*FillIntentResponseV1, error) {
	out := new(FillIntentResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/FillIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetFillIntent(ctx context.Context, in *GetIntentRequestV1, opts ...grpc.CallOption) (*GetIntentResponseV1, error) {
	out := new(GetIntentResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/GetFillIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) FillConfirm(ctx context.Context, in *FillConfirmRequestV1, opts ...grpc.CallOption) (*FillConfirmResponseV1, error) {
	out := new(FillConfirmResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/FillConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CancelIntent(ctx context.Context, in *CancelIntentRequestV1, opts ...grpc.CallOption) (*CancelIntentResponseV1, error) {
	out := new(CancelIntentResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/CancelIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CancelOrder(ctx context.Context, in *CancelOrderRequestV1, opts ...grpc.CallOption) (*CancelOrderResponseV1, error) {
	out := new(CancelOrderResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetBalances(ctx context.Context, in *GetBalancesRequestV1, opts ...grpc.CallOption) (*GetBalancesResponseV1, error) {
	out := new(GetBalancesResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/GetBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetFill(ctx context.Context, in *GetFillRequestV1, opts ...grpc.CallOption) (*GetFillResponseV1, error) {
	out := new(GetFillResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/GetFill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequestV1, opts ...grpc.CallOption) (*GetNodeInfoResponseV1, error) {
	out := new(GetNodeInfoResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Admin/GetNodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
type AdminServer interface {
	ConnectPeer(context.Context, *ConnectPeerRequestV1) (*ConnectPeerResponseV1, error)
	PostOrder(context.Context, *PostOrderRequestV1) (*PostOrderResponseV1, error)
	GetOrder(context.Context, *GetOrderRequestV1) (*GetOrderResponseV1, error)
	FillIntent(context.Context, *FillIntentRequestV1) (*FillIntentResponseV1, error)
	GetFillIntent(context.Context, *GetIntentRequestV1) (*GetIntentResponseV1, error)
	FillConfirm(context.Context, *FillConfirmRequestV1) (*FillConfirmResponseV1, error)
	CancelIntent(context.Context, *CancelIntentRequestV1) (*CancelIntentResponseV1, error)
	CancelOrder(context.Context, *CancelOrderRequestV1) (*CancelOrderResponseV1, error)
	GetBalances(context.Context, *GetBalancesRequestV1) (*GetBalancesResponseV1, error)
	GetFill(context.Context, *GetFillRequestV1) (*GetFillResponseV1, error)
	GetNodeInfo(context.Context, *GetNodeInfoRequestV1) (*GetNodeInfoResponseV1, error)
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_ConnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeerRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ConnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/ConnectPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ConnectPeer(ctx, req.(*ConnectPeerRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_PostOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostOrderRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).PostOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/PostOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).PostOrder(ctx, req.(*PostOrderRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetOrder(ctx, req.(*GetOrderRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_FillIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FillIntentRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).FillIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/FillIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).FillIntent(ctx, req.(*FillIntentRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetFillIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntentRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetFillIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/GetFillIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetFillIntent(ctx, req.(*GetIntentRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_FillConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FillConfirmRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).FillConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/FillConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).FillConfirm(ctx, req.(*FillConfirmRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CancelIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelIntentRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CancelIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/CancelIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CancelIntent(ctx, req.(*CancelIntentRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CancelOrder(ctx, req.(*CancelOrderRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalancesRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/GetBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetBalances(ctx, req.(*GetBalancesRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetFill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFillRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetFill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/GetFill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetFill(ctx, req.(*GetFillRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Admin/GetNodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectPeer",
			Handler:    _Admin_ConnectPeer_Handler,
		},
		{
			MethodName: "PostOrder",
			Handler:    _Admin_PostOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _Admin_GetOrder_Handler,
		},
		{
			MethodName: "FillIntent",
			Handler:    _Admin_FillIntent_Handler,
		},
		{
			MethodName: "GetFillIntent",
			Handler:    _Admin_GetFillIntent_Handler,
		},
		{
			MethodName: "FillConfirm",
			Handler:    _Admin_FillConfirm_Handler,
		},
		{
			MethodName: "CancelIntent",
			Handler:    _Admin_CancelIntent_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Admin_CancelOrder_Handler,
		},
		{
			MethodName: "GetBalances",
			Handler:    _Admin_GetBalances_Handler,
		},
		{
			MethodName: "GetFill",
			Handler:    _Admin_GetFill_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _Admin_GetNodeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
