// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IdentifyRequestV1 struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	ProtocolVersion      int32    `protobuf:"varint,2,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentifyRequestV1) Reset()         { *m = IdentifyRequestV1{} }
func (m *IdentifyRequestV1) String() string { return proto.CompactTextString(m) }
func (*IdentifyRequestV1) ProtoMessage()    {}
func (*IdentifyRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *IdentifyRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentifyRequestV1.Unmarshal(m, b)
}
func (m *IdentifyRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentifyRequestV1.Marshal(b, m, deterministic)
}
func (m *IdentifyRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentifyRequestV1.Merge(m, src)
}
func (m *IdentifyRequestV1) XXX_Size() int {
	return xxx_messageInfo_IdentifyRequestV1.Size(m)
}
func (m *IdentifyRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentifyRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_IdentifyRequestV1 proto.InternalMessageInfo

func (m *IdentifyRequestV1) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *IdentifyRequestV1) GetProtocolVersion() int32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

type IdentifyResponseV1 struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	ProtocolVersion      int32    `protobuf:"varint,2,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentifyResponseV1) Reset()         { *m = IdentifyResponseV1{} }
func (m *IdentifyResponseV1) String() string { return proto.CompactTextString(m) }
func (*IdentifyResponseV1) ProtoMessage()    {}
func (*IdentifyResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *IdentifyResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentifyResponseV1.Unmarshal(m, b)
}
func (m *IdentifyResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentifyResponseV1.Marshal(b, m, deterministic)
}
func (m *IdentifyResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentifyResponseV1.Merge(m, src)
}
func (m *IdentifyResponseV1) XXX_Size() int {
	return xxx_messageInfo_IdentifyResponseV1.Size(m)
}
func (m *IdentifyResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentifyResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_IdentifyResponseV1 proto.InternalMessageInfo

func (m *IdentifyResponseV1) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *IdentifyResponseV1) GetProtocolVersion() int32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

type OrderV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserPubKey           string   `protobuf:"bytes,2,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	MakerAsset           string   `protobuf:"bytes,3,opt,name=makerAsset,proto3" json:"makerAsset,omitempty"`
	TakerAsset           string   `protobuf:"bytes,4,opt,name=takerAsset,proto3" json:"takerAsset,omitempty"`
	Quantity             float32  `protobuf:"fixed32,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	CancelAt             string   `protobuf:"bytes,7,opt,name=cancelAt,proto3" json:"cancelAt,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Memo                 string   `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
	Signature            []byte   `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderV1) Reset()         { *m = OrderV1{} }
func (m *OrderV1) String() string { return proto.CompactTextString(m) }
func (*OrderV1) ProtoMessage()    {}
func (*OrderV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *OrderV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderV1.Unmarshal(m, b)
}
func (m *OrderV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderV1.Marshal(b, m, deterministic)
}
func (m *OrderV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderV1.Merge(m, src)
}
func (m *OrderV1) XXX_Size() int {
	return xxx_messageInfo_OrderV1.Size(m)
}
func (m *OrderV1) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderV1.DiscardUnknown(m)
}

var xxx_messageInfo_OrderV1 proto.InternalMessageInfo

func (m *OrderV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderV1) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *OrderV1) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *OrderV1) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

func (m *OrderV1) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderV1) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderV1) GetCancelAt() string {
	if m != nil {
		return m.CancelAt
	}
	return ""
}

func (m *OrderV1) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *OrderV1) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *OrderV1) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type NotifyOrderRequestV1 struct {
	Order                *OrderV1 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyOrderRequestV1) Reset()         { *m = NotifyOrderRequestV1{} }
func (m *NotifyOrderRequestV1) String() string { return proto.CompactTextString(m) }
func (*NotifyOrderRequestV1) ProtoMessage()    {}
func (*NotifyOrderRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *NotifyOrderRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyOrderRequestV1.Unmarshal(m, b)
}
func (m *NotifyOrderRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyOrderRequestV1.Marshal(b, m, deterministic)
}
func (m *NotifyOrderRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyOrderRequestV1.Merge(m, src)
}
func (m *NotifyOrderRequestV1) XXX_Size() int {
	return xxx_messageInfo_NotifyOrderRequestV1.Size(m)
}
func (m *NotifyOrderRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyOrderRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyOrderRequestV1 proto.InternalMessageInfo

func (m *NotifyOrderRequestV1) GetOrder() *OrderV1 {
	if m != nil {
		return m.Order
	}
	return nil
}

type NotifyOrderResponseV1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyOrderResponseV1) Reset()         { *m = NotifyOrderResponseV1{} }
func (m *NotifyOrderResponseV1) String() string { return proto.CompactTextString(m) }
func (*NotifyOrderResponseV1) ProtoMessage()    {}
func (*NotifyOrderResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{4}
}

func (m *NotifyOrderResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyOrderResponseV1.Unmarshal(m, b)
}
func (m *NotifyOrderResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyOrderResponseV1.Marshal(b, m, deterministic)
}
func (m *NotifyOrderResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyOrderResponseV1.Merge(m, src)
}
func (m *NotifyOrderResponseV1) XXX_Size() int {
	return xxx_messageInfo_NotifyOrderResponseV1.Size(m)
}
func (m *NotifyOrderResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyOrderResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyOrderResponseV1 proto.InternalMessageInfo

type NotifyFillRequestV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserPubkey           string   `protobuf:"bytes,2,opt,name=userPubkey,proto3" json:"userPubkey,omitempty"`
	PreimageHash         []byte   `protobuf:"bytes,3,opt,name=preimageHash,proto3" json:"preimageHash,omitempty"`
	TxHash               []byte   `protobuf:"bytes,4,opt,name=txHash,proto3" json:"txHash,omitempty"`
	IntentId             string   `protobuf:"bytes,55555,opt,name=IntentId,proto3" json:"IntentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyFillRequestV1) Reset()         { *m = NotifyFillRequestV1{} }
func (m *NotifyFillRequestV1) String() string { return proto.CompactTextString(m) }
func (*NotifyFillRequestV1) ProtoMessage()    {}
func (*NotifyFillRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{5}
}

func (m *NotifyFillRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyFillRequestV1.Unmarshal(m, b)
}
func (m *NotifyFillRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyFillRequestV1.Marshal(b, m, deterministic)
}
func (m *NotifyFillRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyFillRequestV1.Merge(m, src)
}
func (m *NotifyFillRequestV1) XXX_Size() int {
	return xxx_messageInfo_NotifyFillRequestV1.Size(m)
}
func (m *NotifyFillRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyFillRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyFillRequestV1 proto.InternalMessageInfo

func (m *NotifyFillRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *NotifyFillRequestV1) GetUserPubkey() string {
	if m != nil {
		return m.UserPubkey
	}
	return ""
}

func (m *NotifyFillRequestV1) GetPreimageHash() []byte {
	if m != nil {
		return m.PreimageHash
	}
	return nil
}

func (m *NotifyFillRequestV1) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *NotifyFillRequestV1) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

type NotifyFillResponseV1 struct {
	TxHash               []byte   `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyFillResponseV1) Reset()         { *m = NotifyFillResponseV1{} }
func (m *NotifyFillResponseV1) String() string { return proto.CompactTextString(m) }
func (*NotifyFillResponseV1) ProtoMessage()    {}
func (*NotifyFillResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{6}
}

func (m *NotifyFillResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyFillResponseV1.Unmarshal(m, b)
}
func (m *NotifyFillResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyFillResponseV1.Marshal(b, m, deterministic)
}
func (m *NotifyFillResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyFillResponseV1.Merge(m, src)
}
func (m *NotifyFillResponseV1) XXX_Size() int {
	return xxx_messageInfo_NotifyFillResponseV1.Size(m)
}
func (m *NotifyFillResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyFillResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyFillResponseV1 proto.InternalMessageInfo

func (m *NotifyFillResponseV1) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

type NotifySettleRequestV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	TxHash               []byte   `protobuf:"bytes,2,opt,name=txHash,proto3" json:"txHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifySettleRequestV1) Reset()         { *m = NotifySettleRequestV1{} }
func (m *NotifySettleRequestV1) String() string { return proto.CompactTextString(m) }
func (*NotifySettleRequestV1) ProtoMessage()    {}
func (*NotifySettleRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{7}
}

func (m *NotifySettleRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifySettleRequestV1.Unmarshal(m, b)
}
func (m *NotifySettleRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifySettleRequestV1.Marshal(b, m, deterministic)
}
func (m *NotifySettleRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifySettleRequestV1.Merge(m, src)
}
func (m *NotifySettleRequestV1) XXX_Size() int {
	return xxx_messageInfo_NotifySettleRequestV1.Size(m)
}
func (m *NotifySettleRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifySettleRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifySettleRequestV1 proto.InternalMessageInfo

func (m *NotifySettleRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *NotifySettleRequestV1) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

type NotifySettleResponseV1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifySettleResponseV1) Reset()         { *m = NotifySettleResponseV1{} }
func (m *NotifySettleResponseV1) String() string { return proto.CompactTextString(m) }
func (*NotifySettleResponseV1) ProtoMessage()    {}
func (*NotifySettleResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{8}
}

func (m *NotifySettleResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifySettleResponseV1.Unmarshal(m, b)
}
func (m *NotifySettleResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifySettleResponseV1.Marshal(b, m, deterministic)
}
func (m *NotifySettleResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifySettleResponseV1.Merge(m, src)
}
func (m *NotifySettleResponseV1) XXX_Size() int {
	return xxx_messageInfo_NotifySettleResponseV1.Size(m)
}
func (m *NotifySettleResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifySettleResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifySettleResponseV1 proto.InternalMessageInfo

type NotifyFillIntentRequestV1 struct {
	IntentId             string   `protobuf:"bytes,1,opt,name=intentId,proto3" json:"intentId,omitempty"`
	UserPubKey           string   `protobuf:"bytes,2,opt,name=userPubKey,proto3" json:"userPubKey,omitempty"`
	CpPubKey             string   `protobuf:"bytes,3,opt,name=cpPubKey,proto3" json:"cpPubKey,omitempty"`
	OrderId              string   `protobuf:"bytes,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Quantity             float32  `protobuf:"fixed32,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	CancelAt             string   `protobuf:"bytes,7,opt,name=cancelAt,proto3" json:"cancelAt,omitempty"`
	Memo                 string   `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	Signature            []byte   `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	MakerAsset           string   `protobuf:"bytes,10,opt,name=makerAsset,proto3" json:"makerAsset,omitempty"`
	TakerAsset           string   `protobuf:"bytes,11,opt,name=takerAsset,proto3" json:"takerAsset,omitempty"`
	Status               string   `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	Price                float32  `protobuf:"fixed32,13,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyFillIntentRequestV1) Reset()         { *m = NotifyFillIntentRequestV1{} }
func (m *NotifyFillIntentRequestV1) String() string { return proto.CompactTextString(m) }
func (*NotifyFillIntentRequestV1) ProtoMessage()    {}
func (*NotifyFillIntentRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{9}
}

func (m *NotifyFillIntentRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyFillIntentRequestV1.Unmarshal(m, b)
}
func (m *NotifyFillIntentRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyFillIntentRequestV1.Marshal(b, m, deterministic)
}
func (m *NotifyFillIntentRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyFillIntentRequestV1.Merge(m, src)
}
func (m *NotifyFillIntentRequestV1) XXX_Size() int {
	return xxx_messageInfo_NotifyFillIntentRequestV1.Size(m)
}
func (m *NotifyFillIntentRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyFillIntentRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyFillIntentRequestV1 proto.InternalMessageInfo

func (m *NotifyFillIntentRequestV1) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

func (m *NotifyFillIntentRequestV1) GetUserPubKey() string {
	if m != nil {
		return m.UserPubKey
	}
	return ""
}

func (m *NotifyFillIntentRequestV1) GetCpPubKey() string {
	if m != nil {
		return m.CpPubKey
	}
	return ""
}

func (m *NotifyFillIntentRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *NotifyFillIntentRequestV1) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *NotifyFillIntentRequestV1) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *NotifyFillIntentRequestV1) GetCancelAt() string {
	if m != nil {
		return m.CancelAt
	}
	return ""
}

func (m *NotifyFillIntentRequestV1) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *NotifyFillIntentRequestV1) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *NotifyFillIntentRequestV1) GetMakerAsset() string {
	if m != nil {
		return m.MakerAsset
	}
	return ""
}

func (m *NotifyFillIntentRequestV1) GetTakerAsset() string {
	if m != nil {
		return m.TakerAsset
	}
	return ""
}

func (m *NotifyFillIntentRequestV1) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NotifyFillIntentRequestV1) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type NotifyFillIntentResponseV1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyFillIntentResponseV1) Reset()         { *m = NotifyFillIntentResponseV1{} }
func (m *NotifyFillIntentResponseV1) String() string { return proto.CompactTextString(m) }
func (*NotifyFillIntentResponseV1) ProtoMessage()    {}
func (*NotifyFillIntentResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{10}
}

func (m *NotifyFillIntentResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyFillIntentResponseV1.Unmarshal(m, b)
}
func (m *NotifyFillIntentResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyFillIntentResponseV1.Marshal(b, m, deterministic)
}
func (m *NotifyFillIntentResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyFillIntentResponseV1.Merge(m, src)
}
func (m *NotifyFillIntentResponseV1) XXX_Size() int {
	return xxx_messageInfo_NotifyFillIntentResponseV1.Size(m)
}
func (m *NotifyFillIntentResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyFillIntentResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyFillIntentResponseV1 proto.InternalMessageInfo

type NotifyFillConfirmRequestV1 struct {
	IntentId             string   `protobuf:"bytes,1,opt,name=intentId,proto3" json:"intentId,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyFillConfirmRequestV1) Reset()         { *m = NotifyFillConfirmRequestV1{} }
func (m *NotifyFillConfirmRequestV1) String() string { return proto.CompactTextString(m) }
func (*NotifyFillConfirmRequestV1) ProtoMessage()    {}
func (*NotifyFillConfirmRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{11}
}

func (m *NotifyFillConfirmRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyFillConfirmRequestV1.Unmarshal(m, b)
}
func (m *NotifyFillConfirmRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyFillConfirmRequestV1.Marshal(b, m, deterministic)
}
func (m *NotifyFillConfirmRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyFillConfirmRequestV1.Merge(m, src)
}
func (m *NotifyFillConfirmRequestV1) XXX_Size() int {
	return xxx_messageInfo_NotifyFillConfirmRequestV1.Size(m)
}
func (m *NotifyFillConfirmRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyFillConfirmRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyFillConfirmRequestV1 proto.InternalMessageInfo

func (m *NotifyFillConfirmRequestV1) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

func (m *NotifyFillConfirmRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type NotifyFillConfirmResponseV1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyFillConfirmResponseV1) Reset()         { *m = NotifyFillConfirmResponseV1{} }
func (m *NotifyFillConfirmResponseV1) String() string { return proto.CompactTextString(m) }
func (*NotifyFillConfirmResponseV1) ProtoMessage()    {}
func (*NotifyFillConfirmResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{12}
}

func (m *NotifyFillConfirmResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyFillConfirmResponseV1.Unmarshal(m, b)
}
func (m *NotifyFillConfirmResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyFillConfirmResponseV1.Marshal(b, m, deterministic)
}
func (m *NotifyFillConfirmResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyFillConfirmResponseV1.Merge(m, src)
}
func (m *NotifyFillConfirmResponseV1) XXX_Size() int {
	return xxx_messageInfo_NotifyFillConfirmResponseV1.Size(m)
}
func (m *NotifyFillConfirmResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyFillConfirmResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyFillConfirmResponseV1 proto.InternalMessageInfo

type NotifyDeleteIntentRequestV1 struct {
	IntentId             string   `protobuf:"bytes,1,opt,name=intentId,proto3" json:"intentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyDeleteIntentRequestV1) Reset()         { *m = NotifyDeleteIntentRequestV1{} }
func (m *NotifyDeleteIntentRequestV1) String() string { return proto.CompactTextString(m) }
func (*NotifyDeleteIntentRequestV1) ProtoMessage()    {}
func (*NotifyDeleteIntentRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{13}
}

func (m *NotifyDeleteIntentRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyDeleteIntentRequestV1.Unmarshal(m, b)
}
func (m *NotifyDeleteIntentRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyDeleteIntentRequestV1.Marshal(b, m, deterministic)
}
func (m *NotifyDeleteIntentRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyDeleteIntentRequestV1.Merge(m, src)
}
func (m *NotifyDeleteIntentRequestV1) XXX_Size() int {
	return xxx_messageInfo_NotifyDeleteIntentRequestV1.Size(m)
}
func (m *NotifyDeleteIntentRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyDeleteIntentRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyDeleteIntentRequestV1 proto.InternalMessageInfo

func (m *NotifyDeleteIntentRequestV1) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

type NotifyDeleteIntentResponseV1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyDeleteIntentResponseV1) Reset()         { *m = NotifyDeleteIntentResponseV1{} }
func (m *NotifyDeleteIntentResponseV1) String() string { return proto.CompactTextString(m) }
func (*NotifyDeleteIntentResponseV1) ProtoMessage()    {}
func (*NotifyDeleteIntentResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{14}
}

func (m *NotifyDeleteIntentResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyDeleteIntentResponseV1.Unmarshal(m, b)
}
func (m *NotifyDeleteIntentResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyDeleteIntentResponseV1.Marshal(b, m, deterministic)
}
func (m *NotifyDeleteIntentResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyDeleteIntentResponseV1.Merge(m, src)
}
func (m *NotifyDeleteIntentResponseV1) XXX_Size() int {
	return xxx_messageInfo_NotifyDeleteIntentResponseV1.Size(m)
}
func (m *NotifyDeleteIntentResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyDeleteIntentResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyDeleteIntentResponseV1 proto.InternalMessageInfo

type NotifyDeleteOrderRequestV1 struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyDeleteOrderRequestV1) Reset()         { *m = NotifyDeleteOrderRequestV1{} }
func (m *NotifyDeleteOrderRequestV1) String() string { return proto.CompactTextString(m) }
func (*NotifyDeleteOrderRequestV1) ProtoMessage()    {}
func (*NotifyDeleteOrderRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{15}
}

func (m *NotifyDeleteOrderRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyDeleteOrderRequestV1.Unmarshal(m, b)
}
func (m *NotifyDeleteOrderRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyDeleteOrderRequestV1.Marshal(b, m, deterministic)
}
func (m *NotifyDeleteOrderRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyDeleteOrderRequestV1.Merge(m, src)
}
func (m *NotifyDeleteOrderRequestV1) XXX_Size() int {
	return xxx_messageInfo_NotifyDeleteOrderRequestV1.Size(m)
}
func (m *NotifyDeleteOrderRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyDeleteOrderRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyDeleteOrderRequestV1 proto.InternalMessageInfo

func (m *NotifyDeleteOrderRequestV1) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type NotifyDeleteOrderResponseV1 struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyDeleteOrderResponseV1) Reset()         { *m = NotifyDeleteOrderResponseV1{} }
func (m *NotifyDeleteOrderResponseV1) String() string { return proto.CompactTextString(m) }
func (*NotifyDeleteOrderResponseV1) ProtoMessage()    {}
func (*NotifyDeleteOrderResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{16}
}

func (m *NotifyDeleteOrderResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyDeleteOrderResponseV1.Unmarshal(m, b)
}
func (m *NotifyDeleteOrderResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyDeleteOrderResponseV1.Marshal(b, m, deterministic)
}
func (m *NotifyDeleteOrderResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyDeleteOrderResponseV1.Merge(m, src)
}
func (m *NotifyDeleteOrderResponseV1) XXX_Size() int {
	return xxx_messageInfo_NotifyDeleteOrderResponseV1.Size(m)
}
func (m *NotifyDeleteOrderResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyDeleteOrderResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyDeleteOrderResponseV1 proto.InternalMessageInfo

type NotifyGetBalancesRequestV1 struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	AssetId              string   `protobuf:"bytes,2,opt,name=AssetId,proto3" json:"AssetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyGetBalancesRequestV1) Reset()         { *m = NotifyGetBalancesRequestV1{} }
func (m *NotifyGetBalancesRequestV1) String() string { return proto.CompactTextString(m) }
func (*NotifyGetBalancesRequestV1) ProtoMessage()    {}
func (*NotifyGetBalancesRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{17}
}

func (m *NotifyGetBalancesRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyGetBalancesRequestV1.Unmarshal(m, b)
}
func (m *NotifyGetBalancesRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyGetBalancesRequestV1.Marshal(b, m, deterministic)
}
func (m *NotifyGetBalancesRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyGetBalancesRequestV1.Merge(m, src)
}
func (m *NotifyGetBalancesRequestV1) XXX_Size() int {
	return xxx_messageInfo_NotifyGetBalancesRequestV1.Size(m)
}
func (m *NotifyGetBalancesRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyGetBalancesRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyGetBalancesRequestV1 proto.InternalMessageInfo

func (m *NotifyGetBalancesRequestV1) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *NotifyGetBalancesRequestV1) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

type NotifyGetBalancesResponse struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	AssetId              string   `protobuf:"bytes,2,opt,name=AssetId,proto3" json:"AssetId,omitempty"`
	Quantity             string   `protobuf:"bytes,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	AddressQuantity      string   `protobuf:"bytes,5,opt,name=AddressQuantity,proto3" json:"AddressQuantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyGetBalancesResponse) Reset()         { *m = NotifyGetBalancesResponse{} }
func (m *NotifyGetBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyGetBalancesResponse) ProtoMessage()    {}
func (*NotifyGetBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{18}
}

func (m *NotifyGetBalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyGetBalancesResponse.Unmarshal(m, b)
}
func (m *NotifyGetBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyGetBalancesResponse.Marshal(b, m, deterministic)
}
func (m *NotifyGetBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyGetBalancesResponse.Merge(m, src)
}
func (m *NotifyGetBalancesResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyGetBalancesResponse.Size(m)
}
func (m *NotifyGetBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyGetBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyGetBalancesResponse proto.InternalMessageInfo

func (m *NotifyGetBalancesResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *NotifyGetBalancesResponse) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *NotifyGetBalancesResponse) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *NotifyGetBalancesResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NotifyGetBalancesResponse) GetAddressQuantity() string {
	if m != nil {
		return m.AddressQuantity
	}
	return ""
}

type NotifyGetBalancesResponseV1 struct {
	Responses            []*NotifyGetBalancesResponse `protobuf:"bytes,1,rep,name=Responses,proto3" json:"Responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *NotifyGetBalancesResponseV1) Reset()         { *m = NotifyGetBalancesResponseV1{} }
func (m *NotifyGetBalancesResponseV1) String() string { return proto.CompactTextString(m) }
func (*NotifyGetBalancesResponseV1) ProtoMessage()    {}
func (*NotifyGetBalancesResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{19}
}

func (m *NotifyGetBalancesResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyGetBalancesResponseV1.Unmarshal(m, b)
}
func (m *NotifyGetBalancesResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyGetBalancesResponseV1.Marshal(b, m, deterministic)
}
func (m *NotifyGetBalancesResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyGetBalancesResponseV1.Merge(m, src)
}
func (m *NotifyGetBalancesResponseV1) XXX_Size() int {
	return xxx_messageInfo_NotifyGetBalancesResponseV1.Size(m)
}
func (m *NotifyGetBalancesResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyGetBalancesResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyGetBalancesResponseV1 proto.InternalMessageInfo

func (m *NotifyGetBalancesResponseV1) GetResponses() []*NotifyGetBalancesResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

func init() {
	proto.RegisterType((*IdentifyRequestV1)(nil), "pb.IdentifyRequestV1")
	proto.RegisterType((*IdentifyResponseV1)(nil), "pb.IdentifyResponseV1")
	proto.RegisterType((*OrderV1)(nil), "pb.OrderV1")
	proto.RegisterType((*NotifyOrderRequestV1)(nil), "pb.NotifyOrderRequestV1")
	proto.RegisterType((*NotifyOrderResponseV1)(nil), "pb.NotifyOrderResponseV1")
	proto.RegisterType((*NotifyFillRequestV1)(nil), "pb.NotifyFillRequestV1")
	proto.RegisterType((*NotifyFillResponseV1)(nil), "pb.NotifyFillResponseV1")
	proto.RegisterType((*NotifySettleRequestV1)(nil), "pb.NotifySettleRequestV1")
	proto.RegisterType((*NotifySettleResponseV1)(nil), "pb.NotifySettleResponseV1")
	proto.RegisterType((*NotifyFillIntentRequestV1)(nil), "pb.NotifyFillIntentRequestV1")
	proto.RegisterType((*NotifyFillIntentResponseV1)(nil), "pb.NotifyFillIntentResponseV1")
	proto.RegisterType((*NotifyFillConfirmRequestV1)(nil), "pb.NotifyFillConfirmRequestV1")
	proto.RegisterType((*NotifyFillConfirmResponseV1)(nil), "pb.NotifyFillConfirmResponseV1")
	proto.RegisterType((*NotifyDeleteIntentRequestV1)(nil), "pb.NotifyDeleteIntentRequestV1")
	proto.RegisterType((*NotifyDeleteIntentResponseV1)(nil), "pb.NotifyDeleteIntentResponseV1")
	proto.RegisterType((*NotifyDeleteOrderRequestV1)(nil), "pb.NotifyDeleteOrderRequestV1")
	proto.RegisterType((*NotifyDeleteOrderResponseV1)(nil), "pb.NotifyDeleteOrderResponseV1")
	proto.RegisterType((*NotifyGetBalancesRequestV1)(nil), "pb.NotifyGetBalancesRequestV1")
	proto.RegisterType((*NotifyGetBalancesResponse)(nil), "pb.NotifyGetBalancesResponse")
	proto.RegisterType((*NotifyGetBalancesResponseV1)(nil), "pb.NotifyGetBalancesResponseV1")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 845 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4d, 0x6f, 0xe3, 0x36,
	0x10, 0x5d, 0x39, 0xb6, 0x63, 0x8f, 0x5d, 0xb4, 0xcb, 0xee, 0x7a, 0xb9, 0xaa, 0x93, 0x75, 0x75,
	0xf2, 0xc9, 0x41, 0x52, 0xa0, 0x40, 0x90, 0x93, 0x9b, 0xa0, 0xa9, 0x51, 0x20, 0x4d, 0x14, 0xd4,
	0x40, 0x7b, 0x93, 0xad, 0x89, 0x23, 0x44, 0x96, 0x14, 0x91, 0x06, 0xea, 0x73, 0x7e, 0x49, 0x8f,
	0x3d, 0x15, 0xe8, 0xff, 0xe8, 0x7f, 0x2a, 0x44, 0x89, 0x22, 0xf5, 0xe1, 0x24, 0x2d, 0x7a, 0xf3,
	0xcc, 0xd3, 0x3c, 0x92, 0x33, 0xef, 0x91, 0x06, 0x08, 0x42, 0x17, 0x27, 0x51, 0x1c, 0xf2, 0x90,
	0x34, 0xa2, 0x85, 0x39, 0x5c, 0x85, 0xe1, 0xca, 0xc7, 0x23, 0x27, 0xf2, 0x8e, 0x9c, 0x20, 0x08,
	0xb9, 0xc3, 0xbd, 0x30, 0x60, 0xe9, 0x17, 0xd6, 0xcf, 0xf0, 0x76, 0xe6, 0x62, 0xc0, 0xbd, 0xbb,
	0xad, 0x8d, 0x8f, 0x1b, 0x64, 0x7c, 0x7e, 0x4c, 0x06, 0xd0, 0x8e, 0x10, 0xe3, 0x99, 0x4b, 0x8d,
	0x91, 0x31, 0xee, 0xda, 0x59, 0x44, 0xc6, 0xf0, 0xb9, 0xa8, 0x5a, 0x86, 0xfe, 0x1c, 0x63, 0xe6,
	0x85, 0x01, 0x6d, 0x8c, 0x8c, 0x71, 0xcb, 0x2e, 0xa7, 0xad, 0x39, 0x10, 0x45, 0xcb, 0xa2, 0x30,
	0x60, 0xf8, 0xbf, 0xf0, 0xfe, 0xde, 0x80, 0xfd, 0x9f, 0x62, 0x17, 0xe3, 0xf9, 0x31, 0xa1, 0xb0,
	0x1f, 0x26, 0x3f, 0x73, 0x3a, 0x19, 0x92, 0x43, 0x80, 0x0d, 0xc3, 0xf8, 0x7a, 0xb3, 0xf8, 0x11,
	0xb7, 0x82, 0xaa, 0x6b, 0x6b, 0x99, 0x04, 0x5f, 0x3b, 0x0f, 0x18, 0x4f, 0x19, 0x43, 0x4e, 0xf7,
	0x52, 0x5c, 0x65, 0x12, 0x9c, 0x2b, 0xbc, 0x99, 0xe2, 0x2a, 0x43, 0x4c, 0xe8, 0x3c, 0x6e, 0x9c,
	0x80, 0x7b, 0x7c, 0x4b, 0x5b, 0x23, 0x63, 0xdc, 0xb0, 0xf3, 0x98, 0xbc, 0x83, 0x56, 0x14, 0x7b,
	0x4b, 0xa4, 0x6d, 0x01, 0xa4, 0x41, 0x52, 0xb1, 0x74, 0x82, 0x25, 0xfa, 0x53, 0x4e, 0xf7, 0x05,
	0x5f, 0x1e, 0x93, 0x21, 0x74, 0x97, 0x31, 0x3a, 0x1c, 0xdd, 0x29, 0xa7, 0x1d, 0x01, 0xaa, 0x04,
	0x21, 0xd0, 0x5c, 0xe3, 0x3a, 0xa4, 0x5d, 0x01, 0x88, 0xdf, 0x49, 0x05, 0xf3, 0x56, 0x81, 0xc3,
	0x37, 0x31, 0x52, 0x18, 0x19, 0xe3, 0xbe, 0xad, 0x12, 0xd6, 0x29, 0xbc, 0xbb, 0x0a, 0x93, 0xce,
	0x8b, 0x46, 0xa9, 0xa9, 0x7e, 0x0d, 0x2d, 0xd1, 0x20, 0xd1, 0xad, 0xde, 0x49, 0x6f, 0x12, 0x2d,
	0x26, 0x59, 0x2f, 0xed, 0x14, 0xb1, 0x3e, 0xc0, 0xfb, 0x42, 0xa9, 0x9c, 0x9c, 0xf5, 0x87, 0x01,
	0x5f, 0xa6, 0xc8, 0xf7, 0x9e, 0xef, 0x2b, 0xce, 0xd7, 0xcc, 0xe0, 0xa1, 0x32, 0x83, 0x07, 0xdc,
	0x12, 0x0b, 0xfa, 0x51, 0x8c, 0xde, 0xda, 0x59, 0xe1, 0x0f, 0x0e, 0xbb, 0x17, 0x53, 0xe8, 0xdb,
	0x85, 0x5c, 0xa2, 0x17, 0xfe, 0x9b, 0x40, 0x9b, 0x02, 0xcd, 0x22, 0x32, 0x84, 0xce, 0x2c, 0xe0,
	0x18, 0xf0, 0x99, 0x4b, 0x9f, 0xfe, 0x4a, 0xe7, 0x97, 0x67, 0xac, 0x89, 0x3c, 0x7f, 0xba, 0x55,
	0x5d, 0x7d, 0x19, 0x9b, 0xa1, 0xb3, 0x59, 0x33, 0x79, 0xe8, 0x5b, 0xe4, 0xdc, 0xc7, 0xd7, 0x1c,
	0x4e, 0x51, 0x35, 0x0a, 0x54, 0x14, 0x06, 0x45, 0xaa, 0xbc, 0x81, 0x4f, 0x7b, 0xf0, 0x51, 0xed,
	0x2a, 0xdd, 0xab, 0x5a, 0xc9, 0x84, 0x8e, 0x27, 0x0f, 0x94, 0x2e, 0x95, 0xc7, 0x2f, 0x8a, 0x39,
	0x91, 0x56, 0x94, 0xa1, 0x59, 0x2b, 0x64, 0xac, 0x9f, 0xa0, 0x59, 0x3c, 0xc1, 0x73, 0x12, 0x2e,
	0x08, 0xb2, 0x5d, 0x16, 0xe4, 0x73, 0x52, 0x96, 0x62, 0xed, 0xec, 0x12, 0x6b, 0xb7, 0x24, 0xd6,
	0x92, 0x15, 0xe1, 0x05, 0x2b, 0xf6, 0x2a, 0x56, 0x1c, 0x40, 0x9b, 0x71, 0x87, 0x6f, 0x18, 0xed,
	0xa7, 0x57, 0x4a, 0x1a, 0x29, 0x1b, 0x7e, 0xa6, 0xd9, 0xd0, 0x1a, 0x82, 0x59, 0x1d, 0x42, 0x3e,
	0x23, 0x5b, 0x47, 0xcf, 0xc3, 0xe0, 0xce, 0x8b, 0xd7, 0xaf, 0x9b, 0x11, 0xcd, 0x6e, 0xa5, 0x99,
	0x9b, 0x0d, 0x48, 0x86, 0xd6, 0x01, 0x7c, 0x55, 0xc3, 0x99, 0x2f, 0x79, 0x2a, 0xe1, 0x0b, 0xf4,
	0x91, 0xe3, 0xbf, 0xd0, 0x85, 0x75, 0x08, 0xc3, 0xba, 0xd2, 0x9c, 0xfa, 0x5b, 0x79, 0x9a, 0x14,
	0x2f, 0x5d, 0x06, 0xda, 0x8e, 0x8d, 0x1d, 0x3b, 0x2e, 0xd4, 0xe5, 0xb4, 0xd7, 0x92, 0xf6, 0x12,
	0xf9, 0x77, 0x8e, 0x9f, 0x4c, 0x9e, 0x15, 0x68, 0xcf, 0xef, 0x1d, 0x2f, 0x50, 0xb4, 0x59, 0x98,
	0x20, 0x62, 0x62, 0xaa, 0x45, 0x59, 0x68, 0xfd, 0x69, 0x48, 0x6b, 0x14, 0x28, 0xd3, 0x15, 0xff,
	0x0b, 0x63, 0xd2, 0xb6, 0x1b, 0x29, 0xee, 0xcc, 0x12, 0x32, 0x16, 0x55, 0xae, 0x1b, 0x23, 0x63,
	0xd2, 0x12, 0x59, 0x98, 0xbc, 0x42, 0xd9, 0xcf, 0x1b, 0xdd, 0x19, 0x5d, 0xbb, 0x9c, 0xb6, 0x7e,
	0x95, 0x2d, 0xaa, 0xd9, 0xf0, 0xfc, 0x98, 0x9c, 0x41, 0x57, 0x46, 0x8c, 0x1a, 0xa3, 0xbd, 0x71,
	0xef, 0xe4, 0x20, 0xb9, 0x6c, 0x77, 0xd6, 0xd8, 0xea, 0xfb, 0x93, 0xbf, 0x5b, 0xd0, 0xbc, 0x0a,
	0x5d, 0x24, 0x67, 0xd0, 0x91, 0x4f, 0x28, 0x79, 0x9f, 0x94, 0x57, 0xde, 0x69, 0x73, 0x50, 0x4c,
	0xe7, 0x33, 0x7a, 0x43, 0x2e, 0xa0, 0xa7, 0x5d, 0xe4, 0x84, 0xaa, 0xe5, 0x8b, 0x3a, 0x30, 0x3f,
	0x56, 0x10, 0x8d, 0x65, 0x0a, 0xa0, 0xc4, 0x4b, 0x3e, 0xa8, 0x4f, 0x0b, 0x8f, 0x80, 0x49, 0xcb,
	0x80, 0x46, 0x71, 0x09, 0x7d, 0xfd, 0x46, 0x24, 0xda, 0x7a, 0xa5, 0xeb, 0xd6, 0x34, 0xab, 0x90,
	0x46, 0x74, 0x0b, 0x5f, 0x94, 0xad, 0x4b, 0x0e, 0x8a, 0x0b, 0x97, 0xdc, 0x63, 0x1e, 0xd6, 0xc3,
	0x1a, 0xe9, 0x1c, 0xde, 0x56, 0xdc, 0x49, 0x4a, 0x65, 0xe5, 0x8b, 0xc0, 0xfc, 0xb4, 0x03, 0xd7,
	0x78, 0x7f, 0x01, 0x52, 0xf5, 0x26, 0xd1, 0x0a, 0x6b, 0xed, 0x6e, 0x8e, 0x76, 0x7d, 0x50, 0xb7,
	0x65, 0xcd, 0x9e, 0xfa, 0x96, 0xeb, 0xdc, 0x6e, 0x7e, 0xda, 0x81, 0xd7, 0xf1, 0x6a, 0xfa, 0xd4,
	0x79, 0xeb, 0xec, 0xae, 0xf3, 0xd6, 0x5a, 0xc1, 0x7a, 0xb3, 0x68, 0x8b, 0xbf, 0x70, 0xdf, 0xfc,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x1d, 0x2b, 0xcc, 0x97, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	Identify(ctx context.Context, in *IdentifyRequestV1, opts ...grpc.CallOption) (*IdentifyResponseV1, error)
	NotifyOrder(ctx context.Context, in *NotifyOrderRequestV1, opts ...grpc.CallOption) (*NotifyOrderResponseV1, error)
	NotifyFill(ctx context.Context, in *NotifyFillRequestV1, opts ...grpc.CallOption) (*NotifyFillResponseV1, error)
	NotifySettle(ctx context.Context, in *NotifySettleRequestV1, opts ...grpc.CallOption) (*NotifySettleResponseV1, error)
	NotifyFillIntent(ctx context.Context, in *NotifyFillIntentRequestV1, opts ...grpc.CallOption) (*NotifyFillIntentResponseV1, error)
	NotifyFillConfirm(ctx context.Context, in *NotifyFillConfirmRequestV1, opts ...grpc.CallOption) (*NotifyFillConfirmResponseV1, error)
	NotifyDeleteIntent(ctx context.Context, in *NotifyDeleteIntentRequestV1, opts ...grpc.CallOption) (*NotifyDeleteIntentResponseV1, error)
	NotifyDeleteOrder(ctx context.Context, in *NotifyDeleteOrderRequestV1, opts ...grpc.CallOption) (*NotifyDeleteOrderResponseV1, error)
	NotifyGetBalances(ctx context.Context, in *NotifyGetBalancesRequestV1, opts ...grpc.CallOption) (*NotifyGetBalancesResponseV1, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Identify(ctx context.Context, in *IdentifyRequestV1, opts ...grpc.CallOption) (*IdentifyResponseV1, error) {
	out := new(IdentifyResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Node/Identify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NotifyOrder(ctx context.Context, in *NotifyOrderRequestV1, opts ...grpc.CallOption) (*NotifyOrderResponseV1, error) {
	out := new(NotifyOrderResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Node/NotifyOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NotifyFill(ctx context.Context, in *NotifyFillRequestV1, opts ...grpc.CallOption) (*NotifyFillResponseV1, error) {
	out := new(NotifyFillResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Node/NotifyFill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NotifySettle(ctx context.Context, in *NotifySettleRequestV1, opts ...grpc.CallOption) (*NotifySettleResponseV1, error) {
	out := new(NotifySettleResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Node/NotifySettle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NotifyFillIntent(ctx context.Context, in *NotifyFillIntentRequestV1, opts ...grpc.CallOption) (*NotifyFillIntentResponseV1, error) {
	out := new(NotifyFillIntentResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Node/NotifyFillIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NotifyFillConfirm(ctx context.Context, in *NotifyFillConfirmRequestV1, opts ...grpc.CallOption) (*NotifyFillConfirmResponseV1, error) {
	out := new(NotifyFillConfirmResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Node/NotifyFillConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NotifyDeleteIntent(ctx context.Context, in *NotifyDeleteIntentRequestV1, opts ...grpc.CallOption) (*NotifyDeleteIntentResponseV1, error) {
	out := new(NotifyDeleteIntentResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Node/NotifyDeleteIntent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NotifyDeleteOrder(ctx context.Context, in *NotifyDeleteOrderRequestV1, opts ...grpc.CallOption) (*NotifyDeleteOrderResponseV1, error) {
	out := new(NotifyDeleteOrderResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Node/NotifyDeleteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NotifyGetBalances(ctx context.Context, in *NotifyGetBalancesRequestV1, opts ...grpc.CallOption) (*NotifyGetBalancesResponseV1, error) {
	out := new(NotifyGetBalancesResponseV1)
	err := c.cc.Invoke(ctx, "/pb.Node/NotifyGetBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	Identify(context.Context, *IdentifyRequestV1) (*IdentifyResponseV1, error)
	NotifyOrder(context.Context, *NotifyOrderRequestV1) (*NotifyOrderResponseV1, error)
	NotifyFill(context.Context, *NotifyFillRequestV1) (*NotifyFillResponseV1, error)
	NotifySettle(context.Context, *NotifySettleRequestV1) (*NotifySettleResponseV1, error)
	NotifyFillIntent(context.Context, *NotifyFillIntentRequestV1) (*NotifyFillIntentResponseV1, error)
	NotifyFillConfirm(context.Context, *NotifyFillConfirmRequestV1) (*NotifyFillConfirmResponseV1, error)
	NotifyDeleteIntent(context.Context, *NotifyDeleteIntentRequestV1) (*NotifyDeleteIntentResponseV1, error)
	NotifyDeleteOrder(context.Context, *NotifyDeleteOrderRequestV1) (*NotifyDeleteOrderResponseV1, error)
	NotifyGetBalances(context.Context, *NotifyGetBalancesRequestV1) (*NotifyGetBalancesResponseV1, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Identify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifyRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Identify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Node/Identify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Identify(ctx, req.(*IdentifyRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_NotifyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyOrderRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).NotifyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Node/NotifyOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).NotifyOrder(ctx, req.(*NotifyOrderRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_NotifyFill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyFillRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).NotifyFill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Node/NotifyFill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).NotifyFill(ctx, req.(*NotifyFillRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_NotifySettle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifySettleRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).NotifySettle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Node/NotifySettle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).NotifySettle(ctx, req.(*NotifySettleRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_NotifyFillIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyFillIntentRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).NotifyFillIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Node/NotifyFillIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).NotifyFillIntent(ctx, req.(*NotifyFillIntentRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_NotifyFillConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyFillConfirmRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).NotifyFillConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Node/NotifyFillConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).NotifyFillConfirm(ctx, req.(*NotifyFillConfirmRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_NotifyDeleteIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyDeleteIntentRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).NotifyDeleteIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Node/NotifyDeleteIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).NotifyDeleteIntent(ctx, req.(*NotifyDeleteIntentRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_NotifyDeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyDeleteOrderRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).NotifyDeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Node/NotifyDeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).NotifyDeleteOrder(ctx, req.(*NotifyDeleteOrderRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_NotifyGetBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyGetBalancesRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).NotifyGetBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Node/NotifyGetBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).NotifyGetBalances(ctx, req.(*NotifyGetBalancesRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Identify",
			Handler:    _Node_Identify_Handler,
		},
		{
			MethodName: "NotifyOrder",
			Handler:    _Node_NotifyOrder_Handler,
		},
		{
			MethodName: "NotifyFill",
			Handler:    _Node_NotifyFill_Handler,
		},
		{
			MethodName: "NotifySettle",
			Handler:    _Node_NotifySettle_Handler,
		},
		{
			MethodName: "NotifyFillIntent",
			Handler:    _Node_NotifyFillIntent_Handler,
		},
		{
			MethodName: "NotifyFillConfirm",
			Handler:    _Node_NotifyFillConfirm_Handler,
		},
		{
			MethodName: "NotifyDeleteIntent",
			Handler:    _Node_NotifyDeleteIntent_Handler,
		},
		{
			MethodName: "NotifyDeleteOrder",
			Handler:    _Node_NotifyDeleteOrder_Handler,
		},
		{
			MethodName: "NotifyGetBalances",
			Handler:    _Node_NotifyGetBalances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}
